### ISSUE TITLE
fix_units_on_coefficient_in_out has no effect

### ISSUE THREAD

**Issue by nhniina** [spine-tools/SpineOpt.jl#1035]
It seems that `fix_units_on_coefficient_in_out` has no effect.

Running SpineOpt with this [input data JSON](https://github.com/user-attachments/files/15888096/fix_units_on_coefficient_in_out.json) should reproduce the bug.

The input data sets `fix_ratio_in_out_unit_flow` = 0.8 and `fix_units_on_coefficient_in_out` = 0.2, as well as `demand` = 1 in the `to_node`.

One would expect to see the following result: `unit_flow(from_node)` = 0.8 * `unit_flow(to_node)` + 0.2 = 0.8 * 1 + 0.2 = 1. As expected, `unit_flow(to_node)` = 1 in the results. However, `unit_flow(from_node)` = 0.8 in the results, which is not what was expected. It looks like `fix_units_on_coefficient_in_out` = 0.2 was not taken into account.

When using min ratio and min units on coefficient instead of the fix counterparts, the parameters work as expected.

SpineOpt version: 63337b52886bbac5e4678740e912e1c6df6040a9

**Comment by DillonJ** [comment]
@nhniina I wonder is this a reporting issue. Did you look at the actual constraints that are generated by printing the model file?

**Comment by Mastomaki** [comment]
I think it is because the `units_on` variable is not considered in `add_variable_unit_flow!(m::Model)`, when replacing variables.

**Comment by DillonJ** [comment]
We'll have to ask @manuelma who is back on Monday. I asked him to look at this specifically so not sure what happened

**Comment by nhniina** [comment]
> I think it is because the `units_on` variable is not considered in `add_variable_unit_flow!(m::Model)`, when replacing variables.

Right. I see that there is a check `iszero(units_on_coefficient(unit=u, node1=n1, node2=n2, _default=0))` in function `_fix_ratio_out_in_unit_flow_simple` which should perhaps avoid this. But is it not working?

**Comment by manuelma** [comment]
> > I think it is because the `units_on` variable is not considered in `add_variable_unit_flow!(m::Model)`, when replacing variables.
> 
> Right. I see that there is a check `iszero(units_on_coefficient(unit=u, node1=n1, node2=n2, _default=0))` in function `_fix_ratio_out_in_unit_flow_simple` which should perhaps avoid this. But is it not working?

Yeah, there was a typo that I fixed in the v0.7 branch but didn't merge into master. Should be ok now in latest master.

**Comment by manuelma** [comment]
> However, unit_flow(from_node) = 0.8 in the results, which is not what was expected

@nhniina I am looking at this, would you expect unit_flow(from_node) = 1.0 in the results? This is what I'm getting after merging the forgotten commit.

**Comment by Mastomaki** [comment]
The update also solves the problem with time series `fix_ratio_out_in_unit_flow` parameters.
