### ISSUE TITLE
Gurobi Error 10003: Name too long (maximum name length is 255 characters)

### ISSUE THREAD

**Issue by hannesfelipe** [spine-tools/SpineOpt.jl#1126]
**Describe the bug**
We are trying to use Gurobi to solve our problem. However, when running a one-year model with a roll_forward of 730h, we get the following error message: Gurobi Error 10003: Name too long (maximum name length is 255 characters). 
We also tried to change the roll_forward to D (but another issue still exists). 

**To Reproduce**
Help us understand how you encountered the bug. Ideally ,give steps to reproduce the behavior, e.g.:
When using this `input_data_model.json` the model is built but then the error message appears when starting the first model run: e.g., 

Model - Window 1 of 12: 2019-01-01T00:00~(4 weeks, 2 days, 10 hours)~>2019-01-31T10:00
Optimizing Model...Gurobi Error 10003: Name too long (maximum name length is 255 characters)

**Expected behavior**
Solving the problem with Gurobi. 

**Screenshots**
see model file. 

**Desktop (please complete the following information):**
- Which SpineOpt version? 0.8.3
- Which toolbox version? 0.8.2
- OS: Windows 11

**Additional context**
When running a shorter period, for instance just 3 days, the model solves.

**Comment by hannesfelipe** [comment]
[input_data_model.json](https://github.com/user-attachments/files/17568465/input_data_model.json)

I forgot the json file. here it is.

**Comment by datejada** [comment]
Hi @hannesfelipe, thanks for the file; it helped me reproduce the error. So, I found a fix by using the Gurobi options. Please look at the attached screenshot for instructions on how to set up the option `IgnoreNames` to avoid Gurobi using the names of the variables. The bright sight is that it doesn't mess with the results, so after solving, it returns the values with the names again (I have double-checked).

Please let me know if this also works for you, and then I will add this trick to the troubleshooting section in the docs.

<img width="782" alt="image" src="https://github.com/user-attachments/assets/053b5ae9-9fd1-4d8b-9f36-fb74c4d65f00">

**Comment by hannesfelipe** [comment]
@datejada thank you for the fast answer. This way, it also worked for me. However, it seems that the results are completely different from the HiGHS runs. I try to have a closer look into it but perhaps you have an idea if this approach changes something in the data structure?
