### ISSUE TITLE
generate_time_slice with optional argument module

### ISSUE THREAD

**Issue by hhoeschle** [spine-tools/SpineOpt.jl#3]
Hi,

we use your SpineModel functionality to represent a temporal resolution in another module. Unfortunately, this leads to the problem that generate_time_slice respectively block_time_slice does not know the functions temporal_block(), ... coming from SpineInterface loading the database.

One option would be to extend the functions as follows:
```julia
function block_time_slices(window_start, window_end; mod::Module=@__MODULE__) 
    d = Dict{Object,Array{TimeSlice,1}}() 
    for blk in mod.temporal_block() 
        time_slices = Array{TimeSlice,1}() 
        blk_spec_start = mod.block_start(temporal_block=blk, _strict=false) 
        blk_spec_end = mod.block_end(temporal_block=blk, _strict=false) 
        blk_start = adjusted_start(window_start, window_end, blk_spec_start) 
        blk_end = adjusted_end(blk_start, window_end, blk_spec_end) 
        time_slice_start = blk_start 
        i = 1 
        while time_slice_start < blk_end 
            duration = mod.resolution(temporal_block=blk, i=i) 
            time_slice_end = time_slice_start + duration 
            if time_slice_end > blk_end 
                time_slice_end = blk_end 
                @warn( 
                    """ 
                    the last time slice of temporal block $blk has been cut to fit within the optimisation window 
                    """ 
                ) 
            end 
            push!(time_slices, TimeSlice(time_slice_start, time_slice_end)) 
            time_slice_start = time_slice_end 
            i += 1 
        end 
        d[blk] = time_slices 
    end 
    d 
end 
 
""" 
    generate_time_slice(window_start, window_end) 
 
Generate and export a convenience functor called `time_slice`, that can be used to retrieve 
time slices in the model between `window_start` and `window_end`. See [@TimeSliceSet()](@ref). 
""" 
function generate_time_slice(window_start, window_end; mod::Module=@__MODULE__) 
    blk_time_slices = block_time_slices(window_start, window_end; mod=mod) 
    # Invert dictionary 
    time_slice_blocks = Dict{TimeSlice,Array{Object,1}}() 
    for (blk, time_slices) in blk_time_slices 
```

We can then forward the module in which the convenience functions are generated. 

Note that `using_spinedb(db_url, SpineModel)` does not solve it because then the convenience functions are unknown to our module...

Any other recommendations are also fine.

I have made a commit here https://github.com/hhoeschle/Spine-Model/commit/cd08a82e24940d407090b94d98260f66e4bda7d9 

Greetings, 
hanspeter

**Comment by ererkka** [comment]
Thanks for the suggestion. I assume this does not break existing code because of the default value `@__MODULE__`? 

/cc @manuelma

**Comment by manuelma** [comment]
Sure, the proposed solution should work and we can do that change right away.

But at the same time I have the feeling this is bigger than that. Should we move the time slice generation part to SpineInterface? Something to discuss.

Also, this is a long shot but did you try something like `using_spinedb(url, module=Main) `

I would try `Main` and `Base` just to see how julia reacts

**Comment by hhoeschle** [comment]
Thanks for the quick reply. I have made a minimal example to show the function calls and problems I have encountered:

```julia
module MyModule

    using SpineModel: generate_time_slice, time_slice
    using Dates

    struct MyModel

        function MyModel(;mod::Module=@__MODULE__)
            self = new()
            init_temporals(;mod=mod)
            return self
        end
    end

    function init_temporals(;mod::Module=@__MODULE__)
        mod_here =  @__MODULE__
        @show "init_temporals", mod_here
        try
            @show mod.temporal_block()
            @show mod_here.temporal_block()
            @show temporal_block()
        catch err
            println(err)
        end
        generate_time_slice(DateTime(0), DateTime(3000);mod=mod)
        @show length(time_slice())
    end

    export MyModel

end


using SpineInterface
db_file = joinpath(@__DIR__, "basic_test_db.sqlite")
db_url = "sqlite:///$db_file"

## Test 1: No Module
# println("="^80)
# using_spinedb(db_url)
# mod =  @__MODULE__
# @show "Main", mod, temporal_block()
# m = MyModule.MyModel()

## Test 2: Main
# println("="^80)
# using_spinedb(db_url, Main)
# mod =  @__MODULE__
# @show "Main", mod, temporal_block()
# m = MyModule.MyModel()

## Test 3: MyModule
# println("="^80)
# using_spinedb(db_url, MyModule)
# mod =  @__MODULE__
# @show "Main", mod, temporal_block()
# m = MyModule.MyModel()

## Test 4: Forwarding module
println("="^80)
using_spinedb(db_url)
mod =  @__MODULE__
@show "Main", mod, temporal_block()
m = MyModule.MyModel(;mod=@__MODULE__)
```

**Comment by manuelma** [comment]
Can you guide us through the example? Where is the output different from what you would expect?

**Comment by hhoeschle** [comment]
only Test 4 delivers the list of TimeSlice (assuming the optional argument is available for generate_time_slice), all other tests fail due to temporal_block being not known ...

Test 1: temporal_block not known in  generate_time_slice, respectively block_time_slices (mimics inital setup from dev branch)
Test 2: same as Test1
Test 3: also fails

**Comment by hhoeschle** [comment]
note I have changed the MWE, using SpineModel: time_slice is removed

**Comment by manuelma** [comment]
Ok, thanks. And do you have any opinion on whether or not this `generate_time_slice` thing should be provided by `SpineInterface`?

**Comment by hhoeschle** [comment]
I am aware of the discussion. I don't have a pronounced opinion. Package managing is quite easy in julia. But as long as kept separate, it might be beneficial if both packages have a check on each other, e.g. SpineModel requires a minimum version of SpineInterface and vice versa...

I expect more functionality to be added to the TimeSeriesCallable in the future (e.g. how to select values, extrapolate, maximum value, first value,  etc... ). It is to be seen if this is understood as part of the database functionality or part of the model functionality.  Personally, I would tend to see this as database functionality, hence, put it in the SpineInterface.

**Comment by ererkka** [comment]
> it might be beneficial if both packages have a check on each other, e.g. SpineModel requires a minimum version of SpineInterface and vice versa...
I agree on SpineModel requiring a version of the interface, but the other way around...? I think the interface should be built to support also other models.

**Comment by mihlema** [comment]
This is a tricky question. On the one hand it would be nice to be able to access the time_slice functions also from other models. However, we have a (SpineOpt-dependent, i.e. model specific) temporal structure (e.g. node__temporal_block relationships). How would this be SpineInterface functionality? I feel the temporal structure is always going to be SpineOpt dependent, and hence would SpineInterface be, if we add the temporal structure there. (I believe this issue probably is even more complex now, as we also have the model argument)

**Comment by mihlema** [comment]
@manuelma I guess this is a won't fix?

**Comment by clizbe** [comment]
Closing due to "won't fix" label and stale status.

**Comment by clizbe** [comment]
Closing due to "won't fix" label.
