### ISSUE TITLE
Option to completely erase contents of url_out if it exists

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#324]
The current behaviour, if I'm not mistaken, if `url_out` exists, is to merge the new results with those existing. If a value exists for the object/relationship, it gets overwritten and if not, it gets added. Conversely, this means that if I have an old result for which there is no corresponding new result, I end up with a mixture of old and new values which is quite dangerous.

I think by default we should consider wiping the output database entirely if it exists, or at least provide an `run_spineopt` argument to specify this behaviour.

**Comment by mihlema** [comment]
Does this also happen if you call Spineopt as a tool in spinetoolbox? If I'm not mistaken, it'll generate an alternative for each new run.

**Comment by DillonJ** [comment]
If this is the case, how does it work then? Is there an argument that controls this behaviour. I admit that I'm not on lastest SpineOpt master so maybe things have changed?

**Comment by manuelma** [comment]
@mihlema is right, toolbox (engine, actually) automatically adds a 'query' to the output url so all results are written to a different alternative for each run.

So yeah, it is controlled by an argument to `run_spineopt()`, but that argument is actually the `url_out` that gets parsed and interpreted by `spinedb_api` underneath.

**Comment by mihlema** [comment]
How to proceed on this? @manuelma I'm not sure if this would be possible, but could we check before writing our parameter back to the db, and - in case the db is not empty- at least provide the user with a warning? @DillonJ what do you think of this option?

I guess alternatively we could have an additional keyword argument to run_spineopt(clear_db=false/true)

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
