### ISSUE TITLE
Bug: `spineopt_operations` model type is not well defined

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#329]
At the moment, the model type `spineopt_operations` corresponds to our default `run_spineopt`. I propose to rename it to `spineopt_standard`. Inline with this, the objective function of this `spineopt_standard` should include investment costs - at the moment they are excluded from the objective function! (At the moment we can't have investments without decomposition it seems). For the decomposed problem, this shouldn't cause problems, as the investment decisions are only associated with the `master problem` instance, and should thus not appear in `spineopt_standard`.
@DillonJ can you confirm?

**Comment by DillonJ** [comment]
Regarding standard vs operations I don't have a strong view except that in the context of a decomposed structure, "standard" has no meaning... i.e. "master problem" and "standard problem" whereas "operations" model still has meaning with and without decomposition. What about "rolling model"? Or "inner" model? Not great ideas - anyone else have an idea for a better name for the operations model?

Regarding the investment costs - the intention was that they are only excluded from the operations model if it is a decomposed model (so you don't have them in both the master and sub-problems). I will check this

**Comment by DillonJ** [comment]
So in `run_spineopt_mp` we set `m.ext[:is_sub_problem]` = true for the operations problem and then we only exclude the investment costs in total_costs.jl if `m.ext[:is_sub_problem]` is true.

Are you finding that for problems with no decomposition the investment costs are excluded?

**Comment by jkiviluo** [comment]
I think @DillonJ is right that 'standard' is not very helpful. Additional suggestions would be 'UCED' or 'scheduling' for the rolling optimization. I would then name investment mode separately, but maybe I'm missing something.

**Comment by mihlema** [comment]
I had a quick chat with jody on this. At the moment even if the type of the model is `spineopt_opertations` investment decisions can be included. I just find the name confusing, because `spineopt_operations` corresponds to our default spineopt model generation script, which can be an investment model with operations included.

For the decomposed problem, we could exclude the investment costs from the total costs, but they should never be part of the subproblem anyways (the `units_invested__temporal_block` should be connected to the master problem - not the subproblem). This is actually also what happens in the script, as there is a typo. The objective function checks for `m.ext[:is_subproblem]` to be `true` to exclude the investment costs, though in the script we assign the value `true` to `m.ext[:is_sub_problem`.

Personally, I would prefer if the generation of cost terms would look the same for all problem, and through the definition of the problem different cost terms are triggered rather than
```
if model_type(model=m.ext[:instance]) == :spineopt_operations
        if m.ext[:is_subproblem]
            [
                :variable_om_costs,
                :fixed_om_costs,
                :taxes,
                :operating_costs,
                :fuel_costs,
                #    :unit_investment_costs,
                #    :connection_investment_costs,
                #    :storage_investment_costs,
                :start_up_costs,
                :shut_down_costs,
                :objective_penalties,
                :connection_flow_costs,
                :renewable_curtailment_costs,
                :ramp_costs,
            ]
        else
            [
                :variable_om_costs,
                :fixed_om_costs,
                :taxes,
                :operating_costs,
                :fuel_costs,
                :unit_investment_costs,
                :connection_investment_costs,
                :storage_investment_costs,
                :start_up_costs,
                :shut_down_costs,
                :objective_penalties,
                :connection_flow_costs,
                :renewable_curtailment_costs,
                :ramp_costs,
            ]
        end
```

If we add new cost terms we'll have to add them in two (or more!) places, I don't like copy and pasting.

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
