### ISSUE TITLE
Do we need `connection_resistance`?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#352]
It was used in the old ptdf calculation to fit to PowerSystems.jl's API, that probably handled AC power flow. The resistance was never used in the ptdf calculation underneath, though. In the new calculation routine 'in-house', we don't need to fit any API so `connection_resistance` is just not used.

I propose we remove the parameter and only reinstate it in the unlikely event we decide we want to have AC power flow in SpineOpt.

Thoughts? @mihlema @DillonJ

**Comment by DillonJ** [comment]
It could be useful if we want to handle losses in some way, even in a DC powerflow

But you are right that it is not currently used and could be reintroduced if required.

**Comment by manuelma** [comment]
Ah, true, I missed that.

I'm just trying to write the concept reference for this parameter and it looks like I'd need to write, "not used at the moment, but eventually...", which doesn't feel right.

**Comment by mihlema** [comment]
I think it's still in the concept reference, but I think we should remove it for now?

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
