### ISSUE TITLE
Finalize `constraint_res_minimum_node_state`

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#356]
I came across some TODOs in this constraint. Just copying them here so maybe @mihlema can elaborate? (Whenever you get the chance of course.) Maybe I can help doing these.

```
# NOTE: the below only works if there's only 1 conventional commodity
# TODO: only for upward reserves? add downward res constraint
# TODO: make this more intuitive
```

**Comment by mihlema** [comment]
I believe this is more limited functionality than bug; should probably find an entry in the docs

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
