### ISSUE TITLE
Support investment for pressure driven gas transfer

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#358]
At the moment, we're assuming that pipelines are not yet invested in. Theoretically, it should be possible to invest in them as candidate units. However, this functionality is not yet tested and needs to be tested/explored/revised.

This is a placeholder issue, to get back to whenever there is resources available.

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
