### ISSUE TITLE
Unused scenario issued by `node_pressure_indices`

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#363]
In the function below, the `s` coming out of `node_pressure_indices(...)` is not used to filter anything below. Feels funny, any comments @mihlema 

```julia
function constraint_min_node_pressure_indices(m::Model)
    unique(
        (node=ng, stochastic_path=path, t=t)
        for (ng, s, t) in node_pressure_indices(m; node=indices(min_node_pressure)) for path in active_stochastic_paths(
            unique(ind.stochastic_scenario
            for ind in node_pressure_indices(m; node=ng, t=t)),
        )
    )
end
```

**Comment by mihlema** [comment]
That's correct, we should probably use `ng in indices(min_node_pressure` and `t in  t_lowest_resolution(time_slice(m; temporal_block=members(node__temporal_block(node=members(ng)))))`
Probably also applies to the `constraint_max_pressure_indices` and  `constraint_min/max_voltage_angle_indices`.
I'll change this whenever I have time

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
