### ISSUE TITLE
`unit_investment_variable_type_list`

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#365]
For the unit investment variable, we use the `unit_investment_variable_type_list` enum, whereas for storage and connection, we use `variable_type_list`. Moreover, we have `unit_online_variable_type_list` with practically the same enumerated values. Is there a reason for this? Couldn't we use the same enum for all of them?

Cc @DillonJ

**Edit**: also, we have `connection_investment_variable_type_list` in the template but is not used.

**Comment by DillonJ** [comment]
Yes, we could use the same for all and should tidy it up

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
