### ISSUE TITLE
Error when generating temporal structure with an incorrect representative_periods_mapping - make more informative?

### ISSUE THREAD

**Issue by junglegobs** [spine-tools/SpineOpt.jl#370]
I have somehow messed something up in my Spine DB, so now when `SpineOpt.generate_temporal_structure!(m)` is called I get the following error: ```no method matching (::SpineOpt.TimeSliceSet)(::Nothing, ::Anything)```. Once I figure out what the issue is, it should be possible to provide a more useful error message.

**Comment by junglegobs** [comment]
I figured out what the error was - I had a `representative_periods_mapping` which was pointing to non existent representative periods.

**Comment by junglegobs** [comment]
@mihlema Any idea how I could check for this, and if it's worth doing?

**Comment by mihlema** [comment]
I'd say definitely worth checking and providing a more meaningful error message. 
In which function is the error thrown? I think it'd make sense to introduce an error message in `_generate_representative_time_slice_mapping`, probably just before `for t in time_slice(m, temporal_block=temporal_block(rep_blk))` ?

**Comment by mihlema** [comment]
Links to #81

**Comment by mihlema** [comment]
Related to #381

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
