### ISSUE TITLE
Moving solver options to spinedb

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#379]
Currently, the user needs to go the the `run_spineopt.jl` *(possibly rename to avoid confusion with SpineOpt's core `run_spineopt.jl`)* and modify solver options there. This is on the one hand not documented, and , depending on the solver, different keywords will be required. One solution to this problem would be to have these solver options as parameters to the model object in the db. Interpretation of the parameter values would happen within run_spineopt (obviously after the db has been read).

model parameters:
- solver; parameter_value_list: Cbc, Gurobi, CPLEX, CLP
- direct_model: *(possibly rename to direct_jump_model)* true, false

But how to go about e.g. MIP gaps? either using the solver API required (as distinct parameter names)
- MIPGap: 0.0001 *(this would be Gurobi)*
- CPXPARAM_MIP_Tolerances_MIPGap: 0.0001 *(this would be CPLEX)*

Or providing a generic mip_gap spinedb parameter, that gets interpreted within spineopt, depending on the selected solver (more work, more difficult to maintain - needs a mapping for all supported solvers.

I think if we just add the most frequent (solver-dependet) parameters (e.g. CPXPARAM_MIP_Tolerances_MIPGap etc.) to the db - automatically read out as solver keywords *(TODO)*, it would be easy to also add new solvers along the way. WDYT?

**Comment by jkiviluo** [comment]
> I think if we just add the most frequent (solver-dependet) parameters (e.g. CPXPARAM_MIP_Tolerances_MIPGap etc.) to the db - automatically read out as solver keywords (TODO), it would be easy to also add new solvers along the way. WDYT?

Sounds like the way to go. As you say, different solvers can have different keywords, so I think the keywords and their parameters should be solver specific already in the SpineDB side. You should be easily able to switch your solver.

**Comment by mihlema** [comment]
I'll hopefully still have a stab at this for e.g. Gurobi, and the MIPGap parameter. Extending this afterwards should be fairly straight forward.

**Comment by mihlema** [comment]
Crunch-time aim:
- [ ] add documentation for user how to change solver option in run_spineopt script
- [ ] possibly add (some) solver options that can be un-/commented in
Roadmap:
- [ ] integrate solver options in db

**Comment by DillonJ** [comment]
Hi folks,

I've been giving this some further thought - we also discussed it a little at the last SpineOpt developer call.

**DB Solver choices**  
I think we were agreed that it would be beneficial to add new model parameters to the database. These could be:
 - `mip_solver` - parameter list of MIP solvers supported in Julia and by Spine (CBC, HiGHS, gurobi, CPLEX.. others?)
 - `mip_solver_options` - a map parameter that contains multiple supported option names and value pairs
 - `lp_solver` - parameter list of LP solvers supported in Julia and by Spine (CLP, HiGHS, gurobi, CPLEX.. others?)
 - `lp_solver_options` - a map parameter that contains multiple supported option names and value pairs

for example, `mip_solver_options` for HiGHS would be:

{
  "type": "map",
  "index_type": "string",
  "data": [
         ["presolve", "on"],
         ["mip_rel_gap", 0.05], 
         [ "threads", 8]
    ]
}
```
**Backwards Compatability:**  
To preserve backwards compatibility with older models, we could have an additional runSpineOpt keyword argument called "use_db_solver_options" or something.

**Package Inclusion:**  
This is where I will need some help. Depending on your choice of solver, the relevant *.jl package needs to be added (e.g. HiGHS.jl), sometimes configured (like CPLEX.jl) and included. We thought that including them all would make SpineOpt too heavy and result in too many additional dependencies, meaning therefore, that if this is to be handled automatically, there needs to be some sort of conditional inclusion of the required packages. Is this possible and if so, what is the best way of doing it?

**Julia Configuration:**  
So perhaps we want conditional inclusion of packages as above - but do we want to assist the user in adding and configuring the packages in Julia via toolbox. Possibly not - we will just have to remind the user it is their responsibility to add and configure the required packages.?

Thoughts? @manuelma @jkiviluo @mihlema @Tasqu ?

**Comment by mihlema** [comment]
Hi @DillonJ 
thanks for this. I'm sure we can discuss some more later, but here already some thoughts I have on this:
- Regarding the `mip_solver` list, I am not entirely sure how this works in practice. I assume there would either be a solver object class or simply the model object class would have a parameter called "solver_type", and the user can choose from the `mip_solver` list. However, how does this then work together with the `mip_solver_options` - i.e. how are `mip_solver_options` linked to `mip_solver` type? (I assume the `mip_solver_options` is a map e.g. "HighS" -> data; but it will be in the users responsibility then to set *both* simultaneously. )
- Regarding the backwards compatibility indeed I think in that case we could just assume SpineOpt defaults. Or that the user (if wanted)  can still overwrite solvers by specifying the in the mip_solver keyword?
- Regarding installing solvers, personally I think it really is probably enough to just link to the documentation for e.g. Gurobi etc. I think if they can install spineopt, spinetoolbox - installing the solvers will probably not be the problem anymore  (HighS as new default solver is gonna ship with spineOpt anyways I assume)

**Comment by jkiviluo** [comment]
Sorry for having no thoughts so far - trying to be on vacation. I don't want to advocate for anything, but just give a thought without really understanding the details in here. 

Would this be easiest to maintain if all the parameters were solver specific? Anyone who wants to use a specific solver would need to use the parameter names that solver requires. Of course allowing for multiple interchangeable solvers. It would then be more like a solver object with a JSON blob for all the parameters. And you could choose which solver object to link with your model instance.

**Comment by DillonJ** [comment]
That would actually be another way of doing it... a solver object class and then an "options" map parameter that had the specific solver option names as keys.

The way I have gone is to have a mip_solver an lp_solver parameter defined on model. Then we have mip_solver_options and lp_solver_options which are map parameters with the solver as the outer key and then option name/value pairs beneath that, as here:

![image](https://user-images.githubusercontent.com/7080191/155577992-b9dbf284-390b-4df4-b4f3-52b5d0a603d9.png)

The advantage of this implementation is that once you have your "library" of solver options, you don't need to change it - whereas the solver option list with solver objects might be a little more difficult to maintain - but I do see benefits. The other issue would be mip solvers and lp solvers - you could use two object classes I guess.

As usual the implementation turned out to be trickier that I thought and I've already spent a little too much time on it :-)
