### ISSUE TITLE
Improve and advance data structure checks

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#381]
Currently, new users are often challenged with a plethora of cryptic error messages, when missing essential elements to SpineOpt. The goal of this issue is to identify common pitfalls, and capture those with explanatory Errors (or warnings if SpineOpt applies some defaults). 

Generally, we can divide input errors into two categories: parameter and object/relationship input errors.

For parameter input errors, the main way forward is to check whether the entered parameter type corresponds to the required parameter type (e.g. duration value for the `roll_forward` parameter etc.). From toolbox side, this functionality has recently been added (@manuelma?). 
On top of that there are some logical checks can be added:
- `model_start`<= `model_end`
- `max_` >= `min_...` (ramps, ratio...)
- `min_operating_point` <= 1
- (to be extended)

For object/relationship classes, especially fundamental relationship can be checked:
- `model` -> if no model exists *error*
- `node/connections/units` with out any relationships to other `nodes/connections/units` -> @warn "isolated"
- `candidate node/unit/connection` not connected to investment temporal block -> @error
- `stochastic_scenario` not defined -> auto create `deterministic` scenario + @warn
- `stochastic_structure` not defined -> auto create `deterministic` scenario + @warn
- missing `stochastic_structure__stochastic_scenario` not defined -> auto create relationships + @warn or @error? For deterministic case this would be okay, for more complex stochastic structures, I think an @error would be safer
- missing `model__temporal_block` (warn already in place)
- (to be extended)

*Alternatively, the output objects could be native to the template - users would need to delete undesired outputs)

**Comment by clizbe** [comment]
Closing due to stale status.
