### ISSUE TITLE
User-friendliness: Convenience shortcuts

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#382]
The general idea of convenience shortcuts is to simplify the model generation for simple use cases (but maintaining of course the original, complex case aswell). An example of this is for example the implementation of the lossless bi-direction connections*. This issue serves as a list of shortcuts to be considered (this also links to #381)

- [ ] bi-directional flow with same loss factor in both directions:  

    - method parameter for connection `bidirectional_directionindependet_loss` (other name suggestions welcome)
    - auto generate `connection__node__node` for reverse direction + `fix/max/min_ratio...` copied from opposing direction
    - auto generate `connection__to/from` nodes

- [X] missing `model__report`,`report`,`output`,`report_output`: autocreate missing items + @warn (see also #381)
    - addressed in 9f98cdaffa651318ac1320e8e998c7cbe5b5d9f7

- other

*(@DillonJ could you confirm that the PTDF based problem is also working **without** this short-cut?)

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
