### ISSUE TITLE
Use case studies to continuously validate SpineOpt code

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#383]
In our existing unit test, constraints and structures are tested on very small scale example. What these unit tests can currently not capture are potential errors with larger,integrated problems, interaction between constraints and also e.g. changes in objective functions. To improve the validation of SpineOpt as a whole it's crucial to also capture these more complex cases. As we already have a couple of case studies available online, and at least some of them compatible with the latest version of SpineOpt, it could be worthwhile to include these case studies into our testing suite. This also comes with the beneficial side effect that our case study repositories will be kept up to date, which will help new users to get into suing SpineOpt.

As a way forward on this:
- [ ] integrate links directly to case study repositories
    - Would this work in practice? I'd like to avoid duplicating the information. But also pulling these case study systems each time we run test, sounds hiddious
    - Alternatively, we could copy the case studies to the /`test` folder in SpineOpt. I'm expecting that this would mean though that the case study repos won't get updated continuously
- [ ] Compare expected results (objective values, cost terms, relevant variables) to be ~= the same

One thing to point out before we move on is that this would increase computational time/complexity of our testing. I'm not sure how many resources we have for such things?

**Comment by mihlema** [comment]
@manuelma I'm not sure if you'd have a good solution for the concern I raised above regarding the location of those case studies. The integration of these links/comparisons of results will be the responsibility of the case study responsible person. As soon as we have the "data location" problem figured out I'll implement A2 as an initial example

**Comment by Tasqu** [comment]
I don't have a strong opinion on this subject, so I'll unassign myself, if that's ok.

**Comment by manuelma** [comment]
>  I'm not sure if you'd have a good solution for the concern I raised above regarding the location of those case studies.

I think we can start by putting the datasets in the SpineOpt repository, for example in JSON format under `examples`. Then we can work on the automatic testing. Synchronizing things with the actual case study repositories can be done in a later step if needed. But maybe it's not needed, or too difficult.

**Comment by Tasqu** [comment]
>I think we can start by putting the datasets in the SpineOpt repository, for example in JSON format under examples. Then we can work on the automatic testing. Synchronizing things with the actual case study repositories can be done in a later step if needed. But maybe it's not needed, or too difficult.

I actually proposed a new file structure for this stuff in #384, as its also relevant for archetypes.

**Comment by Tasqu** [comment]
> I think we can start by putting the datasets in the SpineOpt repository, for example in JSON format under examples. Then we can work on the automatic testing. Synchronizing things with the actual case study repositories can be done in a later step if needed. But maybe it's not needed, or too difficult.

@manuelma Actually, can `run_spineopt` be run on JSON files directly? Should the examples be in a format *(like .sqlite)* that can be run from SpineOpt without going through Spine Toolbox?

**Comment by manuelma** [comment]
> can run_spineopt be run on JSON files directly?

I'm thinking that the test will first import the JSON into a in-memory sqlite db and then pass that to `run_spineopt`, similar to the current unit tests. JSON has to be better than SQLite for version control.

**Comment by Tasqu** [comment]
>I'm thinking that the test will first import the JSON into a in-memory sqlite db and then pass that to run_spineopt, similar to the current unit tests. JSON has to be better than SQLite for version control.

Oh right, I didn't even think of that! That should do the trick indeed!

**Comment by ererkka** [comment]
How about a GitHub Action workflow which clones (a selection of) the case study repositories and tries to execute them with current SpineOpt. This could be triggered manually or once a month or so.

**Comment by manuelma** [comment]
> If they fail, either need to fix SpineOpt or update the case study.

In the last project meeting we discussed that it would be difficult to identify where the issue is exactly for this type of tests, especially if they are run once a month. I imagine we can checkout each commit since last month, when presumably the test was passing, until we find the commit that introduces the failure. Is that good?

In my opinion we should think this through carefully before putting too much effort into it rather than, e.g., unit testing which has proven benefit.

**Comment by ererkka** [comment]
True, it might be even more demanding to find the commit that broke the tests, if they are executed only rarely.

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
