### ISSUE TITLE
Option to leave `connection_lifetime` blanc for speed-up

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#394]
As @CIODWYER pointed out, it might be beneficial to ignore `connection_lifetime` for "short" investment problems, in order to reduce the computational burden (e.g. t_history, linking constraints,..others?).
This should be possible by leaving the lifetime parameter `null`. This is working atm @CIODWYER if I understand correctly? Could you add a note to the #280 possibly (unless it's already in there)

This issue remains open until the economic representation of investments is merged - and functionality is maintained

**Comment by CIODWYER** [comment]
When trying to speed up C3, as the period covered is just one year we don't need to consider the unit_lifetime (economic life is considered in the calculation of the unit_investment_cost which is entered as annualised cost). When the unit_lifetime was left out there was a slight speed up and results well matched so seemed to be ok.

**Comment by DillonJ** [comment]
Just a comment that in general, we shouldn't require things if they aren't entirely fundamental. I wasn't aware that `connection_lifetime` was required.

In general, the investment cost should be sufficient incentive to prevent a model from de-investing in a unit/connection.

@CIODWYER what was your experience playing with the investment temporal blocks? I had a hunch that reducing the investment resolution may be beneficial to give a model more degrees of freedom / less coupling of variables

**Comment by CIODWYER** [comment]
I tried using investment temporal blocks with higher resolution. I don't think there was much of a speed up and I went back to the lower resolution. I can try this again and check it more thoroughly

**Comment by DillonJ** [comment]
Thanks @CIODWYER No need to run anything again!

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
