### ISSUE TITLE
Add SpineOpt.jl (and ancillary packages, SpineInterface.jl etc) to Julia's general registry

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#397]
This would be good and reduce the number of installation instructions by 1, as discussed in last project telco @ererkka

**Comment by mihlema** [comment]
How difficult is this? Otherwise I guess it would be nice to still aim for this in the next two weeks :)

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
