### ISSUE TITLE
SpineOpt Tutorial data outdated

### ISSUE THREAD

**Issue by LeoniePlaga** [spine-tools/SpineOpt.jl#436]
We are at the moment thinking about using SpineOpt for a new project, but if we try any of the tutorial data on https://spine-toolbox.readthedocs.io/en/latest/tutorials.html, we get errors like:
_Warning: The data structure is not the latest version.
Warning: Some items are missing from the input database._
Is there a possiblity to obtain a working example of SpineOpt for the current version? It really can be very simple.

**Comment by DillonJ** [comment]
Hi LeoniePlaga,

Thank you so much for your interest in SpineOpt. The first thing is that these are warnings and not necessarily showstoppers.

I believe that both these warnings will be solved if you load the latest version of the SpineOpt template. 
Warning: The data structure is not the latest version. To load the latest version of the SpineOpt template, in the Spine DB Editor, from the menu (three hirzontal bars in the top right), click on import as follows:
![image](https://user-images.githubusercontent.com/7080191/156589727-baa578b6-41f2-4de8-beb1-27ec4bddb5d6.png)

To change the file type to JSON and click on spineopt_template.json as follows:

![image](https://user-images.githubusercontent.com/7080191/156590071-d26125ec-8b76-4853-9a31-1df5508fa793.png)

If you don't see spineopt_template.json make sure you have navigated to Spine\SpineOpt.jl\templates.

Load the latest version of the SpineOpt template in this way will update your datastore with the latest version of the data structure.

**Comment by mihlema** [comment]
Dear @LeoniePlaga ,
Happy to hear you are considering SpineOpt for your project. 
Indeed unfortunately, the case studies are not necessarily using the latest version of SpineOpt. As @DillonJ mentioned before, the issue could possibly be resolved by simply including the `spineopt_template.json`. Also, I'll attach an updated version of the A2 case study here. Please don't hesitate if you are still encountering issues.
[spineopt_cs_a2.zip](https://github.com/Spine-project/SpineOpt.jl/files/8179392/spineopt_cs_a2.zip)
