### ISSUE TITLE
Explicit initial_values

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#455]
Currently we are using fix_* parameters to set the initial value for some variables. This can work but I feel it's not ideal and it's causing us problems:
 - It has to be set very precisely to have a value in the timeslice immediately preceding the start of the model horizon but must have a "none" value during the model horizon. If we change our model_start then it's not an intial value any more
 - If we want to use timeseries with ignore-year=true so that we don't have to uncessarily repeat the timeseries data, this causes problems too - because the initial value will repeat and we might not want that.

I feel the ideal solution is to simply have explicit initial values. So in addition to `fix_node_state`, for example, we will have, `initial_node_state`. And the same for every other variable that has a fix_* parameter. This way, SpineOpt will then internally always make sure that a fix_value is only set for the timeslice immediately preceding the model window start

**Comment by DillonJ** [comment]
I think this would be a very high-value change - currently specifying intial values is quite tricky and not well documented - this would solve all that.

@manuelma Maybe you could look at this at some point?

**Comment by DillonJ** [comment]
This is a small change I think, but very high value, adding it to milestone TB 0.7

**Comment by manuelma** [comment]
It looks small but one never knows... Some things to consider maybe:

- Is the initial_value applied to the entire history or only to the last time step(s) of the history?
- What happens if both initial_value and fix_value are defined?

**Comment by DillonJ** [comment]
To minimise risk of infeasibilities in the history window, I would apply the initial_value to just the last timeslice before the window start where the variable would otherwise be free and just in the first window

If initial_value and fix_value are defined I would say fix_value wins in order to minimise risk of infeasibilities

**Comment by DillonJ** [comment]
Great to get this done - nice one @manuelma
