### ISSUE TITLE
Keeping case studies up to date

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#459]
Hi all,
it seems like more and more people are interested in using SpineOpt. Unfortunately, most (or all?) of our case studies are outdated. I think it would be good to get the ball rolling on this again.

One possible way forward could be:
- [ ] Upgrade existing case studies; (all or only A case studies?)
- [ ] Integrate case studies as `.json` in SpineOpt repository or
- [ ] link unit tests to case study repositories
- [ ] Define rules for the unit tests (e.g. could we incorporate a rule that the "case study checks" are only run before merging into master?)
- [ ] Test that combination of SpineToolbox-SpineInterface-SpineOpt (and SpineOpt Tool) work

**Comment by DillonJ** [comment]
It would be good to ascertain the status here and let people know which ones work, or could work and then perhaps we should archive case studies which don't work and we don't intend on fixing?

 - I know that case study C3 should be close to working.
 - I believe case study A5 works thanks to a recent small change

Maybe we should identify one or two more to get working?

I think we should also create a new 3-bus unit commitment example that could be used for tutorials. It would be nice to do this for milestone TB 0.7 - could be useful to new SpineOpt users in the Mopo project - I will create a new issue on this.

**Comment by fares2201** [comment]
Hey Dillon, 

Any updates on case study C3 working? If so, where can i find the model?

Thanks,
Fares

**Comment by clizbe** [comment]
@tarskul  Is this related to what we've been doing recently?

**Comment by tarskul** [comment]
@clizbe To some extent yes. I believe that in the Spine project there were some case studies (labeled A and C) in the deliverables. Most of these are pretty outdated (the last time I tried any of them I couldn't get them to work). There is one left in the examples folder (A5) which I'm looking a bit at as that is probably the location where we will put the JSON files from the tutorials.

**Comment by jkiviluo** [comment]
I think we shouldn't try to maintain those case studies when we have a nicer set of tutorials and how-tos that cover all important corners. 

Maybe a bigger example system once we get there though.

**Comment by clizbe** [comment]
If these aren't working I think we should remove them - not nice for people to try using broken stuff.\
Then we can consider if we want them to work or if the tutorials and how-to's are enough.

**Comment by jkiviluo** [comment]
Right. Spine-tools should only have useful repositories.

Maybe move outdated repos to a separate organization and then archive that organization. And mark it as out-of-date.
https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories 

We could also just dump them as long as there is a copy somewhere (in case we want to dust some of them off for a new life).

**Comment by clizbe** [comment]
Okay so I'll close this as unplanned and open a new issue of dumping the old case studies.

**Comment by clizbe** [comment]
@suvayu Do you have a recommendation on how to "archive" old case studies that don't work anymore? Basically we want them removed, so users don't see them, but still be able to recover them *someday* if we ever have the time/desire.

**Comment by suvayu** [comment]
On Fri, 2 Feb, 2024, 15:00 Lauren Clisby, ***@***.***> wrote:

> @suvayu <https://github.com/suvayu> Do you have a recommendation on how
> to "archive" old case studies that don't work anymore? Basically we want
> them removed, so users don't see them, but still be able to recover them
> *someday* if we ever have the time/desire.
>

You can simply delete them (git rm -- path/to/dir). Everything is
recoverable from git history. At a later point, you could always do:

$ git checkout $(git log -1 --format=%h -- path/to/dir)

And you'll be back at the last commit when it was still present.

--
Suvayu

Open source is the future. It sets us free.

**Comment by DillonJ** [comment]
@jkiviluo  @clizbe 

Hopefully not too late, but I know people use the C3 case study and find it useful, so please don’t delete it even if it doesn’t work right out of the box

**Comment by clizbe** [comment]
@DillonJ No worries, nothing is deleted. The repositories are set to read-only (no issues, updates, etc) and there's a note warning users about it. So they can use it all they like, but shouldn't complain if it doesn't work!

**Comment by clizbe** [comment]
But currently we don't have any plans to update them, as we're migrating to Tutorials and How-Tos.
