### ISSUE TITLE
Add min_unit_flow parameter to give lower bound to unit_flow

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#460]
As less cumbersome alternative to minimum_operating_point? @DillonJ please expand description here if needed whenever you get the chance?

**Comment by DillonJ** [comment]
`min_unit_flow` is a simple lower bound on the `unit_flow` variable, which can be a timeseries. `min_operating_point` is different, it's a lower bound that only applies if the unit is online. The difference is
```
      unit_flow >= min_unit flow

vs

      unit_flow >= min_operating_point * unit_capacity * units_online 
```
