### ISSUE TITLE
Return model object also on error

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#467]

**Comment by mihlema** [comment]
I think this also remotely links to a very old merge request #342, allowing users to print conflicts in case aa model is infeasible.
Probably something we should add in the future

**Comment by DillonJ** [comment]
@manuelma I believe this is done, right? Can we close?

**Comment by manuelma** [comment]
I don't think this is done? It was not straightforward as far as I remember...

**Comment by clizbe** [comment]
@manuelma Is this now redundant with #794?
