### ISSUE TITLE
Should output_time_slices also roll?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#468]
I don't think they are rolling now. Does output aggregation work for the second to last windows?

**Comment by DillonJ** [comment]
@manuelma can we close this or is it still relevant?

**Comment by manuelma** [comment]
I think it is still relevant - I mean, I don't really have an answer to my original question yet...

**Comment by clizbe** [comment]
@manuelma Is this something that needs fixing or is it more a Nice to Have?

**Comment by manuelma** [comment]
Needs fixing in my opinion, but maybe not a high priority as nobody seems to be using output resolution at the moment? Maybe we can close and wait for people to complain.
