### ISSUE TITLE
Fix group nodal balance to include all injections from member nodes

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#503]
Currently, there is no link between a node group and its members within nodal balance. The only thing :balance_type_group does at the moment is skip balancing for all members of a node-group that has this balance type.

So we would like to do the following too: If a node group has :balance_type_group, in addition to skip nodal balance for its members, we aggregate the injections of its members and take that as the node injection of the group for the purposes of nodal balance. So nodal balance for a group `ng` would look like:
```
sum(node_injection[n] for n in members(ng)) + sum(connection_flow[c] for c in 'incoming_conns') - sum(connection_flow[c] for c in 'outgoing_conns') == 0
```

instead of just:
```
node_injection[ng] + sum(connection_flow[c] for c in 'incoming_conns') - sum(connection_flow[c] for c in 'outgoing_conns') == 0
```

**Comment by mihlema** [comment]
Interesting idea. I think as long as this expanding happens for `:balance_type_group` only, this should be fine. 
(I.e., as long as we still allow for the functionality where `sum(demand(members)) != demand(group)`, I think current functionality would be maintained).
Alternatively, I guess we could also avoid creating the `node_injection` all together for all member-nodes. I guess this could pontially be a bit more efficient? In that case, we'd just need to make sure that for the `node_injection` constraint, all "internal" storages are expanded.

**Comment by DillonJ** [comment]
Just to note that this was original functionality that got broken somewhere along the way :-)

**Comment by manuelma** [comment]
I am mostly wrong in my diagnostics here, see #563 

Basically when I diagnosed this I missed the fact that constraint_node_injection collects injections into the member nodes automatically. This is because `unit_flow_indices` expands groups behind the scenes. So if you call it with a group, it will return indices for the members.

I would consider not doing this behind `unit_flow_indices` but directly in the constraint expression so it becomes more explicit but it will also becomes more verbose?
