### ISSUE TITLE
Issue with SpineOpt plugin

### ISSUE THREAD

**Issue by RowanPeng** [spine-tools/SpineOpt.jl#515]
Hi,

The problem I face is, when I tried to install plugin of the SpineOpt in the Spine toolbox (shown in the first attached picture), no install dialog appears, and no new toolbar appears (shown in the second attached picture, the plugin option will trun grey and nothing else happens).

I also notice that there is a note saying that SpineOpt plugin is not a requirement for SpineOpt operation (See the third picture). But for all the grid examples in the guidance, they do use the SpineOpt plugin. So, I got confused.

Could you help me to solve the problem with SpineOpt plugin? Or if the SpineOpt plugin is not a requirement for the operation, are there any guidance for using Spine toolbox without the step of SpineOpt plugin?

Regards,

Yuwen Peng
<img width="554" alt="thumbnail_image" src="https://user-images.githubusercontent.com/123334582/214800350-4ece01ea-ec79-4d36-a3bf-31173d545334.png">
<img width="630" alt="thumbnail_image" src="https://user-images.githubusercontent.com/123334582/214800377-8b27d274-82ac-4661-aa38-bb1a67f727e4.png">
<img width="549" alt="thumbnail_image" src="https://user-images.githubusercontent.com/123334582/214800393-ae9c2056-a579-412b-ac46-92e71e6e99cd.png">

**Comment by manuelma** [comment]
Hi @RowanPeng thank you for this!

When did you try to do the plugin installation? It was broken recently due to changing the Spine project repo url and got fixed like yesterday. Can you try reinstalling spinetoolbox and try again?

**Comment by RowanPeng** [comment]
Hi @manuelma,

The issue seems still exists. I tried upgrading the spinetoolbox but still can't get spineopt plugin.

**Comment by manuelma** [comment]
Hi @RowanPeng thanks for the quick reply. Which steps did you follow to reinstall toolbox?

**Comment by RowanPeng** [comment]
Hi @manuelma. I used this 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/123334582/214811656-d22a6976-b966-4c86-93e0-ff9b498441ab.png">

**Comment by manuelma** [comment]
Ah ok... unfortunately the bug hasn't been fixed in that version. And unfortunately, it takes a little bit of effort to do so.

What you could do to get you going immediately is install from sources as described here: https://github.com/spine-tools/Spine-Toolbox#installation-from-sources-using-git

I think we have a problem with the README. Installation from sources (the recomended way at the moment) is only third in the list of installation options. We should move it up, what do you think @jkiviluo @PekkaSavolainen @soininen ?

**Comment by PekkaSavolainen** [comment]
Another option is to install the development (Git) version via pipx like mentioned in readme:

```
python -m pipx install git+https://github.com/spine-tools/spinetoolbox-dev
```

The bug has been fixed there.

**Comment by soininen** [comment]
I'm a bit torn with the installation methods in README.md. On one hand we should promote the recommended way there but in the long run I'd like to make the `pipx` way the recommended one. I guess we could reorder the instructions for now and have another look at the situation once we can provide stable PyPI packages more readily and easily (e.g. after spine-tools/Spine-Toolbox#1934 has been resolved).

**Comment by RowanPeng** [comment]
Hi @PekkaSavolainen  I tried to install the development version, but some errors like this happened. Could you help me with this?
<img width="720" alt="image" src="https://user-images.githubusercontent.com/123334582/214860562-e0c26ee8-403d-4d74-8a93-9d935fcf4637.png">

**Comment by PekkaSavolainen** [comment]
You (@RowanPeng) have a typo. Add space before --force

**Comment by RowanPeng** [comment]
@PekkaSavolainen oops, my bad.
 It works now. Thank you all!

**Comment by DillonJ** [comment]
Looks like we can close this now
