### ISSUE TITLE
Simplify indexing with the stochastic structure

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#527]
At the moment it seems that the stochastic adds a lot of complexity to the process of identifying constraint indices, and maybe some overhead. This issue is about trying to figure out a better implementation without losing the high flexibility of the concept.

**Comment by clizbe** [comment]
@manuelma Is this still relevant or have we fixed this in other restructuring?

**Comment by manuelma** [comment]
Thanks for the heads up @clizbe - I did something so maybe I will close at least for now.
