### ISSUE TITLE
Create SpineOpt Plugin to create SpineOpt binary using PackageCompiler.jl

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#528]
@manuelma has created some very nice and clear instructions how to compile SpineOpt.jl into a DLL that can be used in your project. Here are the instructions: [Ide](https://github.com/spine-tools/SpineOpt.jl#compilation-into-a-julia-system-image)

It would be nice to create a SpineOpt plugin tool that does this for you and so, within your workflow you can create / update the image using the input datastore in your project.

**Comment by manuelma** [comment]
I think the creating of system images should be toolbox native functionality for julia tools in general, not only SpineOpt. I did something in the past that now is broken, but I plan to resucitate it and yes, the idea is to base the image on an exemplary run of the tool using the input DS.

**Comment by DillonJ** [comment]
Sounds great! Is there an issue for this somewhere?

**Comment by manuelma** [comment]
https://github.com/spine-tools/Spine-Toolbox/issues/1225
