### ISSUE TITLE
Performance of saving results degrades badly with rolling horizon

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#537]
I have a model that rolls every 24 hours, meaning 365 windows to solve the full horizon.

When the model rolls, in the first windows, saving results (not writing, just saving) takes a couple of seconds. However it rises steadily each window to around 80 seconds in the final windows. That's roughly 4 hours of results saving for the full run.

We really need a new way to save results as the model rolls

**Comment by manuelma** [comment]
I have been playing with using Arrow.jl to write results. Below is a simple benchmark:

```julia
using SpineInterface
using Arrow
using Dates

function _tabulize(p::Dict)
    [
        (output_name=output_name, entity=entity, index=index, value=value)
        for (output_name, by_entity) in p
        for (entity, val) in by_entity
        for (index, value) in indexed_values(val)
    ]
end

function _dictionarize(table::Arrow.Table)
    d = Dict()
    for (output_name, entity, index, value) in zip(table...)
        by_entity = get!(d, output_name, Dict())
        push!(get!(by_entity, entity, Dict{typeof(index),Any}()), index => value)
    end
    Dict(
        output_name => Dict(entity => indexed_value(vals) for (entity, vals) in by_entity)
        for (output_name, by_entity) in d
    )
end

function _with_arrow(n)
    for i in 1:n
        ts1 = TimeSeries([DateTime(k) for k in i:1000+i], collect(i:1000+i), false, false)
        ts2 = TimeSeries([DateTime(k) for k in i:1000+i], 2 * collect(i:1000+i), false, false)
        p = Dict(:unit_flow => Dict((unit=:pwrplant, node=:elec) => ts1, (unit=:pwrplant, node=:elec2) => ts2))
        Arrow.append("arrowtest.arrow", _tabulize(p))
    end
    table = Arrow.Table("arrowtest.arrow")
    d = _dictionarize(table)
    write_parameters(d, "sqlite:///deleteme.sqlite"; on_conflict="merge")
end

function _without_arrow(n)
    for i in 1:n
        ts1 = TimeSeries([DateTime(k) for k in i:1000+i], collect(i:1000+i), false, false)
        ts2 = TimeSeries([DateTime(k) for k in i:1000+i], 2 * collect(i:1000+i), false, false)
        p = Dict(:unit_flow => Dict((unit=:pwrplant, node=:elec) => ts1, (unit=:pwrplant, node=:elec2) => ts2))
        write_parameters(p, "sqlite:///deleteme.sqlite"; on_conflict="merge")
    end
end

n = 1000
@time _with_arrow(n)
@time _without_arrow(n)
```

The `_tabulize` function converts a dictionary of parameter values into a table, and the `_dictionarize` function does the opposite.

So then, in the `_with_arrow` and `_without_arrow` functions we simulate a run_spineopt loop where for each window, we have a dictionary of parameter values we want to write to the DB. The former (with arrow) just tabulizes and writes the values into an arrow file. When the loop is done, it reads the file, dictionarizes the data and writes it to the DB. The latter (without arrow) just writes the parameter values to the DB at every iteration - the current situation.

The with arrow version is about 5 times faster with `n = 1000`. I believe it's worth using it.

**Comment by DillonJ** [comment]
Oh wow - nice work @manuelma
