### ISSUE TITLE
Check that timeseries data covers full model window plus lookahead

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#538]
The most infuriating thing that seems to happen 11 times out of 10 is that a model fails in the last window because of a "nothing" due to insufficient timeseries data covering the model window plus the lookahead. You just need a single nothing value to lose a full run. Thanks to the write_as_roll run_spineopt argument, these days you don't loose everything, but it's still a major inconvenience. 

We have the ignore_year and repeat timeseries flags that help with this - but of course, out of many time series, I had failed to set this flag for one of them and was punished!

It would be very easy to work out in advance, the first and last timeslice of each rolling window and check that each parameter has a value and if not, give an error or a warning - this would be incredibly useful. In the simplest case, if we could just check the last timeslice (accounting for lookahead) and this would be extremely useful!

**Comment by manuelma** [comment]
> It would be very easy to work out in advance, the first and last timeslice of each rolling window and check that each parameter has a value

I agree it would be rather easy (not very) to do it once but a real nightmare to maintain: every time I add/change a parameter I need to remember to also update the code that does the checking and make sure that it does it well!

A better option in my opinion is to do a dry-run before actually solving anything: just generate the model and roll it to the end while updating coefficients and all that stuff, but never solving or saving results or writing outputs. Then when the dry-run is completed, we roll back the temporal structure to the begining and start the real run.

**Comment by DillonJ** [comment]
I have the feeling that the dry run will take some time for larger models and perhaps reduce the benefit... I feel like you would get greater benefit from checking either just the last timeslice of the model or the beginning and and of each window the structure will generate.

You could just check all parameters with timeseries values to avoid having to maintain some kind of parameter list.
