### ISSUE TITLE
Fix_unit_flow_op does not work with input value Map

### ISSUE THREAD

**Issue by elinaspyrou** [spine-tools/SpineOpt.jl#545]
I want to use fix_unit_flow_op with input value Map because I have multiple operating points for a unit and I only want to fix the flow_op(s) for an hour before the model starts to initialize my model. Unfortunately, I see an error 
Fixing variable values...MethodError: no method matching isnan. 

My understanding is that the following line " if !isnan(fix_value_)" in run_spineopt_standard.jl throws the error.

Do you have any suggestion on code updates for the run_spineopt_standard.jl or modeling initial values for unit_flow_op?

I am looking forward to your response.

Many thanks,
Elina

**Comment by DillonJ** [comment]
In a recent update, we introduced `initial_[variable_name]``. So now you can do this a lot more easily - you just need to set a value for the parameter `initial_unit_flow_op`.

You will need to pull the latest SpineOpt from Github

**Comment by manuelma** [comment]
Thanks for this issue @elinaspyrou 

Would it be possible to also post the part of the traceback that comes after Fixing variable values...MethodError: no method matching isnan?

Also, can you show the Map you're trying to use on fix_unit_flow_op? Maybe a screenshot from DB editor?

**Comment by DillonJ** [comment]
@elinaspyrou I believe the short answer to  your question is that:
 1. You can use the new parameter `initial_unit_flow_op` to define the initial value for `unit_flow_op` but generally, we otherwise don't have a way to define time varying values for array parameters - but this is something we should address

**Comment by elinaspyrou** [comment]
Hi @DillonJ and @manuelma I used the new variable initial_unit_flow_op and it works. @manuelma thank you for your patience as I had to recreate the case to save all screenshots and log files (attached)
[log_repo.txt](https://github.com/spine-tools/SpineOpt.jl/files/10823034/log_repo.t
![Map_content](https://user-images.githubusercontent.com/51838512/221153058-b00f5af5-f6b5-4c00-bdca-b030b14ca0d2.png)
![Parameter_fix_unit_flow_op](https://user-images.githubusercontent.com/51838512/221153062-e8d5cc96-d2c6-40a1-b335-d395feb800d3.png)
xt)
