### ISSUE TITLE
StackOverflowError caused by too many temporal index

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/SpineOpt.jl#546]
A model with a bit more time steps (3-month horizon in hourly resolution on my machine) seems to cause `StackOverflowError` in writing reports, no matter it uses rolling or attempts to solve the full horizon. Shorter model horizons work as usual. [This sample DB](https://github.com/spine-tools/SpineOpt.jl/files/10812577/Main.Input.Data.Store.zip) should be able to replicate the issue.

**Comment by manuelma** [comment]
Hi @nnhjy is it possibly to post the entire traceback you get?

**Comment by manuelma** [comment]
I see the error - will fix asap

**Comment by manuelma** [comment]
@nnhjy should work better after pulling latest SpineOpt and SpineInterface master branches. Please let me know whenever you get the chance.

**Comment by nnhjy** [comment]
Nice, it is working now. Thanks!
