### ISSUE TITLE
Group balance not working as intended?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#563]
I don't know if this is broken or not, but @DillonJ handed me a model with a node group that has balance_type_group and also a demand. The group has no units or connections connected directly to it, so the assumption seems to be that the group demand is going to be 'balanced' by the units and connections connected to the member nodes.

This seems logical, however it's not the way SpineOpt works at the moment. We have:

```
node_injection == sum(flow from units) - sum(flow to units) - demand        [constraint_node_injection]
```

which in the case of our node group (that has no units connected to it) results in `node_injection == -demand`. This seems fine, however we'd also need to impose that the node_injection of the group is equal to the sum of the node_injection of all the member nodes. We don't do this anywhere. We just have:

```
sum(node_injection of member nodes) == sum(flow from connections) - sum(flow to connections)        [constraint_nodal_balance]
```

So the node_injection of the group is never used in constraint_nodal_balance. In other words, there's nothing linking the demand of the group with the node_injection of the members. Will try to fix now.

**Comment by mihlema** [comment]
Didn't have time to look into this yet, but reminds me of another issue from recently #503, not sure if they are related.

**Comment by manuelma** [comment]
Turns out I was completely wrong here. The link was already there as constraint_node_injection 'expands' groups when collecting unit_flow indices. So the unit_flows that make it into the constraint are from the member nodes. It looks like this

```
group node_injection == sum(flow from units into member nodes) - sum(flow from member nodes into units) - group demand
```

which is exactly what we want, namely having the group demand covered by the flows into the member nodes. Will fix.

**Comment by manuelma** [comment]
> Didn't have time to look into this yet, but reminds me of another issue from recently https://github.com/spine-tools/SpineOpt.jl/issues/503, not sure if they are related.

They are completely related, thank you @mihlema (also related in my inability to diagnose the issue correctly)
