### ISSUE TITLE
Hydropower Plant: use node_state of water reservoir to consider head height

### ISSUE THREAD

**Issue by JaKehrl** [spine-tools/SpineOpt.jl#567]
Hi, 

we are currently using SpineOpt to model a large scale hydropower plant. The head height has an impact on the potential energy in the storage. Therefore, we would like to consider the head height but do not really know how to implement it in SpineOpt. Any help would be appreciated :) 

Please find attached an overview of the problem (with literature background) as well as a mini model. 

[Head Height (Problem Formulation).pdf](https://github.com/spine-tools/SpineOpt.jl/files/10962014/Head.Height.Problem.Formulation.pdf)

[Hydropower_test_model.zip](https://github.com/spine-tools/SpineOpt.jl/files/10962011/Hydropower_test_model.zip)

**Comment by DillonJ** [comment]
Hi JaKerl,

Do you absolutely need to know the head height? You can determine the maximum stored energy when the head height is at it's maximum and this will then be the node_state_cap for your storage. You can also determine the amount of stored energy when the head height is at it's lowest permissable and this will be node_state_min. You will always be able to translate from the stored energy volume back to the head height but perhaps it's not necessary to use the head height directly in the model as the relationship between head  height and stored energy will generally not be linear.

**Comment by JaKehrl** [comment]
Hi DillonJ, 
thanks for the message! We are not directly keen in the head height itself. We just mentioned it to provide some background information on why it is important to not only assume one efficiency factor. We have information available about the relationship of stored volume to potential energy of the stored volume. So as per below image, we would like to create constraints that evaluate the potential energy that runs through the penstock. 

This means, for example: 
If StoredWater <20.000hm3 THEN WaterThroughPenstock*EnergyConversionBase*1.0
If 20.000hm3<=StoredWater <30.000hm3 THEN WaterThroughPenstock*EnergyConversionBase*1.01

whereas 

- WaterThroughPenstock describes the water in m3 that runs through the penstock
- EnergyConversionBase is a factor, that calculates the potential energy of the water as if the head height was at its minimum
- 1.0 or 1.01 are factors, that take the head height into account. These are set by the user/us since we know the increase of gained potential energy per volume increase. 

To conclude, this approach would piece-wise linearize the problem avoiding a non-linear problem. 

Can this be easily implemented as a user constraint without taking too much computational power?


![image](https://user-images.githubusercontent.com/124700754/227888041-ed6db7e6-4635-4306-8f27-ef6c2790c1e3.png)

**Comment by clizbe** [comment]
@JaKehrl Were you able to figure something out or is this still an active Issue?

**Comment by JaKehrl** [comment]
@clizbe we have made an assumption that the head height can be neglected as it would have caused a maximum deviation of 2% for the annual energy yield.
