### ISSUE TITLE
`constraint_ratio_out_in_connection_intact_flow` makes no sense?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#584]
At the moment, all this constraint is doing is imposing `connection_intact_flow['in'] == connection_intact_flow['out']`. There's no ratio at all, see the source https://github.com/spine-tools/SpineOpt.jl/blob/master/src/constraints/constraint_ratio_out_in_connection_intact_flow.jl

@DillonJ it seems you are the original author of this file, do you recall what was going on here? I feel we need to remove this constraint altogether.

**Comment by DillonJ** [comment]
This is only relevant where there are investments with ptdf-based load flow. In this formulation we can't model losses, so we have to make this assumption it's consistent with the other functionality here - we have 4 connection flow variables and we only need 2 of them and we pick 2 to involve in the constraints and set the other two equal. It doesn't interefere with other functionality

**Comment by DillonJ** [comment]
@manuelma maybe the issue is the constraint name - we just need to force the flows to be equal - maybe we should rename the constraint accordingly to avoid confusion?

**Comment by manuelma** [comment]
Thanks very much for the explanation @DillonJ - I will rename the constraint and update the docstring.
