### ISSUE TITLE
Removing extra available variables

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#600]
V_units_available is just V_units_invested_available plus existing capacity and is not necessary. Should be replaced with expression.

**Comment by clizbe** [comment]
We should keep an eye out for others like this.

**Comment by clizbe** [comment]
If I'm understanding it correctly, this constraint determines the value of units_available:
constraint_units_available.jl

In that file, it says (simplified):
units_available - units_invested_available <= number_of_units

But according to 
[jkiviluo (Juha Kiviluoma)](https://matrix.to/#/@jkiviluo-63c2d17b6da0373984bd05ba:gitter.im)
 it should be an equality, and therefore can be replaced with an expression.

Which is correct? Or am I misunderstanding the model?

**Comment by manuelma** [comment]
Looking at the formulation, `units_available` will always be equal to `units_on` in the optimal solution.

We have `units_on <= units_available` in a constraint, but it always binds in the solution.

So we should remove `units_available` for performance. Will do that now.
