### ISSUE TITLE
Allow nodes to be sources of commodities

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#604]
Nodes could be sources or sinks with a price (i.e. commodities). Currently one needs to create a unit with vom cost to provide node with the energy/matter to be consumed.

Will reduce number of variables (unit_flow and node_injection into fuel node)

**Comment by clizbe** [comment]
@jkiviluo Is this still relevant or does @DillonJ 's comment cover it?
Seems related to #598

**Comment by DillonJ** [comment]
@clizbe this can be closed… balance_type and nodal_balance_sense allow this functionality
