### ISSUE TITLE
Model creates unnecessary history variables

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#606]
At the moment it's assumed that history is always needed (at least 1 step) and creates variables for them. These could be avoided by checking better when history is actually needed (dynamic constraints for the node).

**Comment by DillonJ** [comment]
I think this is more to do with the fact that unit commitment variable and constraints are created for units that don't need them as discussed in https://github.com/spine-tools/SpineOpt.jl/issues/612. If the unit commitment variabe is needed, then the history variables are also needed since we at least to look back one timeslice to capture starts.

**Comment by manuelma** [comment]
So #162 is one thing for sure; but this one is also a thing in my opinion. We can check if no history is needed at all (if node_state = false for all nodes, roll_forward is nothing, and some other conditions probably) and in that case fully deactivate the history.

But #612 seems way more impactful, and priority.

**Comment by DillonJ** [comment]
@manuelma but history is needed any time a duration parameter is involved, not just for `node_state`... e,g, for min_up_time, min_down_time ramp rates etc.

Don't we have code that computes the amount of history required based on all these duration parameters?

**Comment by manuelma** [comment]
Yes, we can tight it up. It could be that no history is needed for some particular cases too.

**Comment by jkiviluo** [comment]
Indeed, I think the idea from the Amsterdam workshop was to check the length of history needed for each variable instead of defaulting to the worst case.

**Comment by DillonJ** [comment]
We discussed this just now and agreed to look at doing the following:

Calculating required history on a per-variable basis. E.g. for `units_on` we determine the required history for each unit based on the max of `min_up_time` and `min_down_time` for that unit - and the same for other variables. This will help with model size and performance.

The second thing is that timeslices will be needed for the greatest history needed and we should make this calculation for investment timeslices and operational timeslices.

**Comment by datejada** [comment]
Closed by https://github.com/spine-tools/SpineOpt.jl/pull/940
