### ISSUE TITLE
Add option to have no `units_on` variable when not needed

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#612]
Now we have `unit_online_variable_type` and the options are:
  - `unit_online_variable_type_linear`
  - `unit_online_variable_type_binary`
  - `unit_online_variable_type_integer`

This forces generation of the unit commitment variable and all the associated unit commitment constraints for many units that don't need one at all (e.g. renewable units and units with no `min_operating_point` or `unts_on_cost`, `start_cost` or `start_up_unit_flow` (there may be other parameters that need `units_on`.

We should add the option to have `unit_online_variable_type` = `unit_online_variable_type_none`. This should have the effect of not creating the units_on variable. If any parameters are defined that rely on units_on being there, we should issue a warning in `check_data()`

In my opinion this would be the highest value item to implement from what was discussed in the deep dive today.

**Comment by manuelma** [comment]
So I think one easy, very seamless way to implement this is to replace the unneeded variable by a Float at the generation step. That way we only need to change the part where variables are generated and not every single constraint where the value appears or may appear in the future. Will try to do it that way.
