### ISSUE TITLE
Implement multi-year investments

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#613]
- [ ] Propose new formulation
- [ ] Check everyone agrees on formulation on paper (give 2 weeks for comments)
- [ ] Implement in code
- [ ] Present changes at meeting in January

**Comment by datejada** [comment]
This issue is related to this pull request where there is a new proposal to consider multi-year investments in SpineOpt 

https://github.com/spine-tools/SpineOpt.jl/pull/448

**Comment by clizbe** [comment]
I think this issue is related: #326

**Comment by datejada** [comment]
Close this issue in favor of #908
