### ISSUE TITLE
fix_[variable_name] that varies by window and is relative to window start time

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#650]
**Is your feature request related to a problem? Please describe.**
We have a rolling model and wish to take long term storage trajectories from a longer term model. We only want to fix the final value in each rolling window to the corresponding value from the longer term model solution

**Describe the solution you'd like**
We want to be able to specify a fix_[variable_name] that is different for each window and also relative to each window's start time. For example, if we had a model with a 60-day window that rolled every 24h we want to fix only the last value of each 60-day window to the correspoding value from the solution from the longer term model.

**Describe alternatives you've considered**
There are a few ways we could do this:
 - A new final_[variable_name] parameter that could be a map parameter with an analysis time that specifies the window start time to which it applies
 - Extend the fix_[variable_name] funtionality to that 1. it can be a map where the first key is an anaylsis time specifying the window start time and 2. where the actual value can be specified relative to the window start time (maybe that is already possible, but I'm not sure).

**Additional context**
I believe this is functionality that will be generally very useful when passing information between long and short term models.

Thoughts?

**Comment by manuelma** [comment]
> Extend the fix_[variable_name] funtionality to that 1. it can be a map where the first key is an anaylsis time specifying the window start time and 2. where the actual value can be specified relative to the window start time (maybe that is already possible, but I'm not sure).

How is this different than just specifying the fix value as a time series? The user would have to build a map with analysis time plus offsets, instead of the more direct time series where the time stamps are already the result of analysis time plus offset. Or I am missing something?

**Comment by DillonJ** [comment]
The use case is that I want to fix the last value and only the last value of each rolling window and that value will be different each window. Come to think of it -  perhaps you're right - it can be accomplished by a time series with NANs in between each hourly value

**Comment by DillonJ** [comment]
Actually, no - in our use case, we have a 120 day look-ahead and want only to fix the first and last value, but we want to do that in each window and in each window, the values are different, so that's not possible with a timeseries

**Comment by manuelma** [comment]
Yes, the time series with NaNs would work - although is not very convenient. The user needs to 'calculate' the entire time series so it matches the particular model_start, model_end, and roll_forward values set for the model. If the latter change then the fix_value time series needs to change as well.

We have the initial_variable parameter, so we could have the final_variable parameter I suppose. The question is how do we make this window-dependent.

> Actually, no - in our use case, we have a 120 day look-ahead and want only to fix the first and last value, but we want to do that in each window and in each window, the values are different, so that's not possible with a timeseries

Then a map can do it I think. Setting analysis time as the outermost key would allow us to set fix values independently for each window. But it becomes even more complicated to maintain as per the above.

**Comment by DillonJ** [comment]
Looks like this is implemented and we can close this issue
