### ISSUE TITLE
Improve formulations and implementations for ramping and reserves

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/SpineOpt.jl#654]
We would like to make it as "correct, fast, and flexible to use" as possible ...

Specific actions:

### Documentation 
- [x] Add a tutorial on ramping and reserve use in SpineOpt
- [ ] Create a table in the documentation that shows which constraints appear in SpineOpt when we have specific parameters.
- [x] Add the constraint "unit flow capacity with ramps" to the documentation and rename it to avoid misleading the users (the name suggests ramping constraint, but is creating an upper bound for the capacity)

### Constraint unit flow capacity with ramps
- [x] Include the unit committed for the non-spinning downward reserve in this constraint according to the proposed formulation.
  - [x] Change the constraint
  - [x] Modify/add tests
  - [x] Change the documentation
- [x] Double-check the activation of this constraint since, in a simple example appears the “constraint_unit_flow_capacity” (basic version), instead of this detailed version.

### Constraint on minimum operating point
WIP: branch 654-constraint-minimum-operating-point
- [x] It is necessary to subtract the downward reserves (including the non-spinning reserve) in LHS and the unit committed to the spinning reserve in the RHS
  - [x] Change the constraint
  - [x] Modify/add tests
  - [x] Change the documentation
  
### Ramp up, ramp down, and split ramps constraints

- [x] The RHS is different in SpineOpt for both ramping constraints from the proposed formulation
- [x] Since the reserves are treated as nodes, unnecessary constraints appear in the model. So, we need to clean the code to only create the necessary constraints. For example, in the ramp-up constraint appears:
Flow ramp + upwards reserve <= RHS (correct)
Flow ramp - downwards reserve <= RHS (unnecessary)
- [x] Double-check possible changes in other existing constraints in SpineOpt related to ramps, such as max_start_up_ramp, max_shut_down_ramp, min_start_up_ramp, and min_shut_down_ramp.

Note: Issue #603 looks relevant.

**Comment by DillonJ** [comment]
Some thoughts on this.

Some high level comments that I think are important:

 - I think we should support reserves that are not linked to ramping - this is more computationally efficient. For example, just to constraints: 1. Reserve < capacity - flow (headroom constraint) and 2. Reserve < capability (where capability is the maxium capability over the reserve time frame that might be related to ramping but also other considerations but there is no explicit link with ramping (computationally efficient).
 - I think we should support ramping not related to reserves, i.e. simple ramp up and ramp down limits. Do we currently support these?

Apart from these main considerations, here are some other thoughts:

 - I think there is some benefit in implementing reserves with an explicit object class in database - it feels like there is some concensus on this.
 - I also think there is benefit in implementing it using existing flow variables and using proprocessing as originally suggested by @mihlema 

Maybe the next step is a prototype db design (which could be independent of the implementation) and some pseudo code for what the pre-processing might look like?

**Comment by manuelma** [comment]
I removed it from the code already, https://github.com/spine-tools/SpineOpt.jl/issues/702

**Comment by gnawin** [comment]
Constraint on minimum operating point and its test and documentation have been updated. The PR #742  is ready for review.

**Comment by gnawin** [comment]
Issue #751 is about creating a tutorial on reserves

**Comment by datejada** [comment]
Done in #786 #787 #789
