### ISSUE TITLE
SpineOpt formulation

### ISSUE THREAD

**Issue by elinaspyrou** [spine-tools/SpineOpt.jl#657]
Is it possible to see the SpineOpt formulation for a model run? My understanding is that depending on the parameters my input database has, constraints/variables are being added or not. Does SpineOpt already store the formulation in the directory or is there a way to ask SpineOpt to create that file and store it in a specific location?

**Comment by tarskul** [comment]
The model that SpineOpt sends to JuMP can be saved to a file. It is not the nicest file to read but at the very least you can find the used variables and parameter values.

To write this file you need to set the "write_mps_file" parameter of the model object to "write_mps_always".

SpineOpt will write the file to the working directory, i.e. the spine toolbox work folder, which is typically in your user directory e.g. C:\Users\username\.spinetoolbox\work\run_spineopt_gibberish_toolbox\model_diagnostics.mps

**Comment by DillonJ** [comment]
Hi @elinaspyrou,

There are a few ways to do this. The main way is to call `write_model_file(m, filename)` where m is a reference to your model and filename is the filename you want the model file written to. The call to run_spineopt() returns m... usually in your run_SpineOpt tool, you will have m=run_spineopt(). Then in the julia console when SpineOpt has finished executing and the console remains open, you can call `write_model_file(m, filename)`.

You will find that this file is very large, so if you are debugging, often it's helpful to create a minimum example of your model with only one or two timesteps. 

Hopefully that helps!

**Comment by elinaspyrou** [comment]
Thank you very much @tarskul  and @DillonJ. I really appreciate the clear and quick responses and tips.

**Comment by DillonJ** [comment]
Also, in the call to run_spineopt() you can add the keyword argument optimize=false so it will just build the model and not attempt to solve it - this can make things faster when you're debugging
