### ISSUE TITLE
Connection Investment

### ISSUE THREAD

**Issue by OliverLinsel** [spine-tools/SpineOpt.jl#660]
Good morning everyone,
as mentioned yesterday in the monthly Spine call, I was unsuccesfull with implementing connection investment. I made a minimum energy system with only two nodes and a connection between them. To test whether the model settings allow investment at all and to ensure "emergency" feasibility, I also included an expensive bypass unit that can be invested in case the connection does not work.
I already filled in most of the connection investment parameters. Also, I tried to set "fix_connections_invested" and "fix_connections_invested_available" to 10 - this lead to the model crashing.
As you can see, the unit investment works. Therefore I would assume, that the basic model parameters (stocastic_structure/temporal_block etc) are ok. Do you see which parameter is wrong?

Thank you very much!
Oliver
[pipeline_invest_MVP.zip](https://github.com/spine-tools/Spine-Toolbox/files/11673718/pipeline_invest_MVP.zip)

**Comment by DillonJ** [comment]
@OliverLinsel I've moved this issue to the SpineOpt.jl repo as I believe this is where it belongs for now... but it might be a toolbox or API issue that is the root cause - let's investigate

**Comment by DillonJ** [comment]
Hi @OliverLinsel I ran this and it works for me. I see that the connection is invested in.

Are you running the latest SpineOpt. I can see from your SpineDB template you are missing some recent changes (like the `initial_*` parmeters for example.

Also, would it be possible to post the SpineOpt output, and any console output that you see - this would help a lot.

**Comment by OliverLinsel** [comment]
@DillonJ thank you very much. Yes, in the current configuration it does use the pipelines, but I thought this would be because I already gave it connection_capacity. The result export however does not display any connection_investment_costs although they are listed in the model report output. Therefore, I assumed that no investment was made.
What parameter triggers the investment calculation?
You can find my result Excel attached:

[exported_db_url@Data Store 2.xlsx](https://github.com/spine-tools/SpineOpt.jl/files/11675121/exported_db_url%40Data.Store.2.xlsx)

Yes, it is possible that it is not the most recent version, since we try to use the same version in our research project and we have to ensure that everything still runs after each update so we dont do them every time a new version comes out. So this might be an issue too.

**Comment by DillonJ** [comment]
Hi Olivier,

You need to add `report__output` output relationships for the outputs you want to see. In this case:
 - connections_invested
 - connections_invested_available

**Comment by OliverLinsel** [comment]
Hey Jody - oh my, that is actually the case. Thanks a lot.
Yes that was a problem before, but it somehow stopped doing that in my reduced model. Maybe I accidentally did something right I did wrong before.
Thank you :)

**Comment by OliverLinsel** [comment]
Hey Jody - oh my, that is actually the case. Thanks a lot.
Yes that was a problem before, but it somehow stopped doing that in my reduced model. Maybe I accidentally did something right I did wrong before.
Thank you :)
