### ISSUE TITLE
Unit tests fail on windows with julia 1.6 and 1.8

### ISSUE THREAD

**Issue by tarskul** [spine-tools/SpineOpt.jl#665]
For a few of the latest branches, the unit tests fail on windows.

If you push changes to one of the branches on github, the unit tests automatically run. Lately they fail for windows specifically. Both for julia 1.6 and julia 1.8.

@manuelma found that the error message was related to HiGHs with the error message:

Running HiGHS 1.5.3 [date: 1970-01-01, git hash: 45a127b78]
Copyright (c) 2023 HiGHS under MIT licence terms
ERROR:   Option 'threads' is set to 1 but global scheduler has already been initialized to use 8 threads. The previous scheduler instance can be destroyed by calling Highs::resetGlobalScheduler().
Unable to find solution (reason: OTHER_ERROR)

It might be a consequence of the real problem but it is worth checking whether it is the cause of the problem.

According to the HiGHs documentation the default number of threads should be 0 such that HiGHs can automatically choose the number of threads. From the error it seems that threads is explicitly set to 1. However, we do not set this to 1 in any of the tests. When looking at the template in the code it seems that the threads are set to 8 for the milp solver and unspecified for the lp solver. The documentation of HiGHs also states that parallellism only works under certain conditions. Perhaps we set it to 8 and the solver sets it back to 1? In that case we could try to set the default in the template to 0 and see whether that solves it?

On the other hand, that does not necessarily make sense. Because if that was the issue, the error should have appeared sooner and across the different operating systems.... Still, I suppose it can't hurt to check.

**Comment by manuelma** [comment]
I managed to fix this on friday by setting threads to 0 by default as you suggested. That indeed solves the problem on all platforms. Thanks!
