### ISSUE TITLE
Teams meeting for Q&A does not work

### ISSUE THREAD

**Issue by elinaspyrou** [spine-tools/SpineOpt.jl#682]
Dear Spine Tools team, 
i joined the Teams meeting for exchange, Q&A today from multiple devices and I kept getting the same message that the host of the meeting will let me in when the meeting starts. Have the details of the meeting changed?

Many thanks,
Elina

**Comment by tarskul** [comment]
I'm not aware of a meeting yesterday. As far as I'm concerned, the early-users meetings hold place every first tuesday of the month (as stated in the readme of the project) which would be next week.

**Comment by elinaspyrou** [comment]
Thanks @tarskul for the response. Is there a public link for the first Tuesday meetings?
Here is the link I found for the last Wed of month meetings on the spine tools github repo:
![Spine_meeting](https://github.com/spine-tools/SpineOpt.jl/assets/51838512/b5b09d8e-c78c-4ac8-98f7-b215852ea655)

**Comment by tarskul** [comment]
Am I communicating with the past? `:-) Because when I go to either the spine tools page or the spineopt page it says in both cases that the meetings are on the first tuesday...

![image](https://github.com/spine-tools/SpineOpt.jl/assets/120471470/1cd860c9-f801-485c-9f54-4562452fa842)

**Comment by tarskul** [comment]
Ah, I see the problem. For some reason members of the project see something different from the public. We will update this as soon as possible. (I'll have to ask around because I've never done that myself.)

**Comment by mihlema** [comment]
Hi @elinaspyrou ,
apologies for the confusion! We tried to update the meeting invite in all the different places, but must have overlooked this. I have now updated the public site, thanks @tarskul for investigating. Hope you'll come join us next Tuesday!
