### ISSUE TITLE
Update on the technical lifetime of a unit/storage/connection constraint

### ISSUE THREAD

**Issue by datejada** [spine-tools/SpineOpt.jl#689]
Create a method so that the user can select either ">=" or "==" in the technical lifetime constraint and update the documentation

https://spine-tools.github.io/SpineOpt.jl/latest/mathematical_formulation/constraints/#Technical-lifetime-of-a-unit

**Comment by datejada** [comment]
FYI: Look to the nodal balance constraint to look for inspiration.

**Comment by hannesfelipe** [comment]
Is there an update on this issue? Today, I realised that the "unit_investment_lifetime" parameter is only the minimal lifetime. For longer modelling periods it would be helpful to have a maximum lifetime.

**Comment by tarskul** [comment]
@hannesfelipe We have not started on this issue yet but we should be rather soonish (give or take a few weeks).

**Comment by datejada** [comment]
Note: consider the comments in #601 for the implementation

**Comment by hannesfelipe** [comment]
@datejada thank you for the update. I think the approach with the ">=", "==", and "<=" options is very good. I am looking forward to use the option in our model.

**Comment by datejada** [comment]
> @datejada thank you for the update. I think the approach with the ">=", "==", and "<=" options is very good. I am looking forward to use the option in our model.

Hi @hannesfelipe, the changes are now available in the master branch for your use and testing. BR, Diego
