### ISSUE TITLE
variable_Template.initial_node_state error

### ISSUE THREAD

**Issue by RowanPeng** [spine-tools/SpineOpt.jl#696]
Hi there,

I am trying to construct a GB power model by using Spine. I faced this error issue when I tried to add a hydrogen energy storage node. I kindly request any ideas about how to solve this issue.

Thank you for your time.

Yuwen
![image](https://github.com/spine-tools/SpineOpt.jl/assets/123334582/e52d3882-e4c3-450f-aee6-3824f1fe9e17)

**Comment by manuelma** [comment]
Thank you for creating this issue! We need to fix this, but in the meantime, a work around is to just restart julia.
