### ISSUE TITLE
Incude reporting of connection_intact_flow automatically when using Benders

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#711]
Incude reporting of `connection_intact_flow` automatically when using Benders

Currently you get an error if you haven't added `connection_intact_flow` to your reporting object

**Comment by DillonJ** [comment]
I've fixed this with the above commit but there may be a nice solution @manuelma

**Comment by manuelma** [comment]
This doesn't seem related to benders. I think it happens when you try to report connection_avg_intact_throughflow but not connection_intact_flow

**Comment by manuelma** [comment]
Well, it is related to benders in the end. We are saving outputs and doing the postprocessing for the master problem too which is unnecessary in my opinion. Will fix...
