### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alireza64z** [spine-tools/SpineOpt.jl#720]
When running a template project, the following errors appear:
Running SpineOpt...
ERROR: LoadError: ArgumentError: Package SpineOpt does not have HiGHS in its dependencies:

**Comment by DillonJ** [comment]
Hi @Alireza64z 

How did you install SpineOpt.jl? Are you using the latest version? Are you using SpinePeriods by any chance?

**Comment by Alireza64z** [comment]
> 
Thank you for your response. I want to confirm that I followed the instructions given on the website (https://github.com/spine-tools/SpineOpt.jl) correctly.

**Comment by DillonJ** [comment]
Thanks @Alireza64z. In those instructions, there are different options for installing SpineOpt.jl. I would always recommend option 3b (installation from sources) as the Julia repository is not always up to date.

**Comment by DillonJ** [comment]
@manuelma can you have a look at this and see if the Julia repo needs to be updated?

**Comment by clizbe** [comment]
If this is still a problem, please open a new issue with more info.
