### ISSUE TITLE
Question on node_slack_penalty

### ISSUE THREAD

**Issue by HaoyuFang0909** [spine-tools/SpineOpt.jl#730]
As far as I know whether it is surplus or shortage, as long as the node is not balanced, the same penalty, `node_slack_penalty`, will be paid per unit. I wonder if there's any method to split the penalty of surplus and shortage of a node? Thanks

**Comment by DillonJ** [comment]
Hi @HaoyuFang0909,

You're correct and presently there is no way to have a different slack for positive or negative slacks... but you could accomplish this by connecting a dummy unit instead to your node with a `unit__to_node` relationship (the flow on this corresponding to a positive node slack) and a `unit__from_node` relationship (the flow on this corresponding to a negative node slack). You can then set the fuel_cost parameter on each relationship differently and this will correspond to your slack penalty. You also have the additional freedom here to set capacities on the flows, thereby implementing a maximum slack.

The nicer long term solution would be to activate and penalise the negative and positive slacks independently, which we should do

**Comment by HaoyuFang0909** [comment]
Very nice solution! Thank you! @DillonJ

**Comment by HaoyuFang0909** [comment]
By the way, is there a way to separately count the fuel cost from this 'dummy unit'?
