### ISSUE TITLE
When viewing results in a data store it is no longer possible to select an option from alternative tree at the same time as object tree

### ISSUE THREAD

**Issue by SeanByrne08** [spine-tools/SpineOpt.jl#749]
**Describe the bug**
Before the most recent update when viewing my results I could select a run from the alternative tree as well as an object from the object tree e.g. electricty node. Since the update it no longer allows me to select both, this requires looking through more results to find the information that you are looking for.

**To Reproduce**
1. Run a model which outputs data to a data store.
2. have more than 1 set of results available
3. try to select a specifc run as well as the results from a specific object

**Comment by DillonJ** [comment]
Hi @SeanByrne08 

The selection behaviour has changed and now selecting an alternative will clear other selections. Now you need to ctrl+click to select the alternative in addition to the other selections in tree
