### ISSUE TITLE
Documentation: Case Study A5

### ISSUE THREAD

**Issue by aporrasc** [spine-tools/SpineOpt.jl#755]
To define some relationship parameter values in a row, e.g., unit__from_node (cs-a5-unit__from_node-relationship-parameter-values.txt), the list of object names is separated by ",", which results in an error. Please modify the corresponding attachments with the correct way to implement several object_name_list in a row.

**Comment by clizbe** [comment]
@aporrasc Thanks for pointing this out. We're actually planning on removing the case studies, as they're quite out of date.
