### ISSUE TITLE
Restore unit capacity functionality

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#763]
**Describe the bug**
Hi all,
just had a meeting with @datejada and @gnawin looking through the unit capacity constraint, and related topics.
What we noticed is that the unit capacity constraint indices are currently not created correctly. This link back to the commit 12ae0ab
![image](https://github.com/spine-tools/SpineOpt.jl/assets/40030652/10073b1f-8fb5-45eb-9e94-81129b0c0a01)
The intended behavior of this constraint is that is created for the lowest generation of the unit flow variables (rather than the combination with units on variables resolution). This insures that the unit_capacity of unit flows doesn't exceed unit_capacity at any point in time. We still, however, want to include the units_on variables in the stochastic path to make sure that al relevant stochastic scenarios are captured appropriately.
Through zipping the to variables indices together in commit 12ae0ab, relevant timeslices for the unit capacity constraint are not generated appropriately. It might be possible to zip them but only for the unit flow lowest resolution, but I'm not sure if we then still see the units_on stochastic scenarios (if they are not fully contained but only overlapping timeslices), but I think they would be included in the path?

I have not looked through other files of that particular commit, but there might be other constraints with similar issues. @manuelma I think you originally proposed this change, let me know if you have any thoughts on this.

**Comment by gnawin** [comment]
I can see the same indexing is also used for constraint_minimum_operating_point. That part has, till now, remained the same in the change of that constraint related to PR #742.
