### ISSUE TITLE
Error in running Spine opt

### ISSUE THREAD

**Issue by Alireza64z** [spine-tools/SpineOpt.jl#766]
I attempted to run Case C3 which I downloaded from the GitHub repository. However, when I started Spine Opt, I encountered the following error. Could you please provide guidance on what I should do?

julia> # Running julia run_spineopt.jl
ERROR: LoadError: MethodError: no method matching run_spineopt()

Closest candidates are:
  run_spineopt(::String)
   @ SpineOpt C:\Users\Alireza\SpineOpt.jl\src\run_spineopt.jl:79
  run_spineopt(::String, ::Union{Nothing, String}; upgrade, mip_solver, lp_solver, add_user_variables, add_constraints, log_level, optimize, update_names, alternative, write_as_roll, use_direct_model, filters, log_file_path, resume_file_path)

**Comment by DillonJ** [comment]
Hi @Alireza64z,

This case study is quite old and works with an older version on SpineOpt and Toolbox. This was part of the original Spine project. We don't have plans right now to bring it up to date. 

Looking at that specific error, the run_spineopt() function takes the input DB and out DB urls as arguments.

The first step could be to follow the tutorial here https://spine-tools.github.io/SpineOpt.jl/latest/index.html to gain a basic understanding of how things work, and then perhaps you might be better equipped to figure it out?

**Comment by jkiviluo** [comment]
We should at least mark the old case study repositories. In the best case with a SpineOpt version number where the case study would still work.

**Comment by Alireza64z** [comment]
In order to temporarily run some old case studies, the following modifications may be necessary: 
1. Drag a Load template and connect it to the input and output database. Also, drag the items from available resources to command linear arguments.
2. Remove the existing "Run SpineOpt" box drag a new one from the SpineOpt toolbox and make the re-connection to input and output databases. Again, drag the items from available resources to command linear arguments.

By following these steps, the case study should run correctly and provide the desired results. Note that this solution has been tested and works for Case Study C3.

**Comment by clizbe** [comment]
As discussed in #459 and tasked in #803, this case study will be removed. Tutorials will be the standard going forward.
