### ISSUE TITLE
Get rid of model__temporal_block and model__stochastic_structure

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#811]
For some time now we have been accepting a single model in SpineOpt DBs. This is because we simplified the decomposition data structure which previously relied on defining multiple model entities in SpineOpt - and this needed model__temporal_block and model__stochastic_structure.

If we plan to keep things that way, I'd suggest we get rid of model__temporal_block and model__stochastic_structure - they are not needed and complicate the initial setup unnecessarily, especially for new users.

Any thoughts? @DillonJ ?

**Comment by jkiviluo** [comment]
Would this also extend to SpineOpt input DB? I don't know the details, but in principle I think it would be great if both temporal aspects could be in one class.
