### ISSUE TITLE
Improve the How to print the model in the documentation

### ISSUE THREAD

**Issue by datejada** [spine-tools/SpineOpt.jl#822]
**Is your feature request related to a problem? Please describe.**
The current how it is not fully complete. The user needs a couple more steps to get the model constraints. To properly work you need:

SpineOpt.write_model_file(m; file_name="C:\\github-repos\\SpineOpt.jl\\model")

This is because the function is not exported. So, if you want to access the function from the terminal, then you need to use the command above.

**Describe the solution you'd like**
Have an example of julia code with more details

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tarskul** [comment]
Maybe instead of updating the documentation, we can export the function. There is no reason not to, right?

**Comment by datejada** [comment]
@tarskul I'm okay with that solution, too. But, in any case, the example and the fix in the docs would be nice to have in this section, too.

Are there any criteria to determine which functions are exported or not? @manuelma

**Comment by datejada** [comment]
@tarskul we commented on this during the developers meeting, @manuelma agrees that it is better to export the function. So, I'll update the PR for your review. I'll let you know when is ready.
