### ISSUE TITLE
(Monotonically) decreasing incremental heat rate

### ISSUE THREAD

**Issue by danajhen** [spine-tools/SpineOpt.jl#826]
Hi,

we would like to depict that our efficiency (energy) is increasing in the level of output. We tried to use operating points and incremental_heat_rate (as the inverse of efficiency), but quickly found out that the latter can only be used for monotonically increasing cases, the opposite of what we were trying to achieve. Is there an option to use the parameter for a decreasing case or even a mixed case, where efficiency is increasing at first and decreases after a certain point? Or do you have to build user_constraints in any case?

Thank you in advance

**Comment by DillonJ** [comment]
@danajhen you need to set ordered_unit_flow_op=true. See here, https://spine-tools.github.io/SpineOpt.jl/latest/concept_reference/Parameters/#ordered_unit_flow_op

**Comment by nnhjy** [comment]
@danajhen Basically you can realise what you mentioned by using the [user_constraint](https://spine-tools.github.io/SpineOpt.jl/latest/advanced_concepts/user_constraints/). And as @DillonJ said, the key to having decreasing efficiency is by setting `ordered_unit_flow_op=true`.
