### ISSUE TITLE
Ramping constraints 

### ISSUE THREAD

**Issue by r0sv** [spine-tools/SpineOpt.jl#831]
Hello!
Sorry, maybe I'm wrong because I have little experience using SpineOpt. 
After successfully implementing the example of a simple system and the example from the webinar, I tried to apply Ramping constraints.
https://spine-tools.github.io/SpineOpt.jl/latest/tutorial/ramping/
unit_capacity =100
start_up_limit = 0.1
initial_unit_flow=0
But the power plant is turned on at full load (100 MW) without a gradual increase in power (e.g. 10 MW).
In addition, the constraints "ramp_up_limit" or "rump_down_limit" are not executed at all. The simulation ends with an error.
I have upgraded spineopt. I'm using the latest templates (spineopt_template and basic_model_template). It did not help.
Please, help me to understand.

**Comment by datejada** [comment]
@r0sv would you mind following the steps I commented here? https://github.com/spine-tools/SpineOpt.jl/discussions/832#discussioncomment-8000268
Thanks!

**Comment by datejada** [comment]
Closing this issue since it was solved in #832
