### ISSUE TITLE
SpineOpt crashes when installing it from the Spine Julia Registry

### ISSUE THREAD

**Issue by Mastomaki** [spine-tools/SpineOpt.jl#880]
**Describe the bug**
SpineOpt crashes when installing it from the Spine Julia Registry. In the `prepare_spineopt()` function. 

**To Reproduce**
Run any model using the version installed from  Spine Julia Registry.

**Screenshots**

```
Stacktrace:
 [1] difference(left::Module, right::Module)
   @ SpineInterface ~/.julia/packages/SpineInterface/Vk3IS/src/api/core.jl:625
 [2] macro expansion
   @ ~/.julia/packages/SpineOpt/ifkx1/src/run_spineopt.jl:233 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/SpineOpt/ifkx1/src/util/misc.jl:40 [inlined]
 [4] prepare_spineopt(url_in::String; upgrade::Bool, log_level::Int64, filters::Dict{String, String})
   @ SpineOpt ~/.julia/packages/SpineOpt/ifkx1/src/run_spineopt.jl:230
```

**Desktop (please complete the following information):**
- latest registry version. 

**Additional context**
Obviously the SpineInterface version is incompatible. Works with SpineInterface v0.11.13.

**Comment by Mastomaki** [comment]
There's no entry for the latest version in Compat.toml. Could this be the reason?

**Comment by clizbe** [comment]
Duplicate, see #835
