### ISSUE TITLE
SpineOpt Upgrading is not working

### ISSUE THREAD

**Issue by Yil2** [spine-tools/SpineOpt.jl#902]
**Describe the bug**
It seems the 'up SpineOpt' does not work. 
There are some students working in Spine and they all met the same error. The error said no method matching and need to upgrade SpineOpt. However, when they used 'up SpineOpt' in Julia, it did not upgrade anything.

**To Reproduce**
Instead of using 'up SpineOpt' they used 'update' to upgrade all and solved the error.

**Comment by clizbe** [comment]
Hello!
"up" should work the same as "update" so might be a problem with their configuration?

Can they try entering package mode in the Julia terminal, by pressing ] and then typing:
```Pkg.jl
pkg> up SpineOpt
```
https://docs.julialang.org/en/v1/stdlib/Pkg/
