### ISSUE TITLE
Introduce units_out_of_service to schedule maintenance outages

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#903]
To increase the flexibility and utility of SpineOpt, it would be useful to be able to schedule maintenance outages. A simple way to do this is to add a new variable called `units_out_of_service`. 

At any time, t, `units_available(u, t)` is then `number_of_units(u, t)` + `units_invested_available(u, t)` - `units_out_of_service(u,t)`

Then we have a new parmeter `scheduled_outage_duration` which is the amount of time a unit must be out on maintenance over the optimisation horizon. The idea is that this would be used in a long term model, perhaps along with scheduling of long term storage/hydro.

Then we need a constraint similar to `min_up_time` to ensure that the outage is taken as a continuous block

My understanding is that the most efficient way to implement would be to have the following analogs:

`units_out_of_service` = `units_on`
`units_taken_out_of_service` = `units_started_up`
`units_returned_to_service` = `units_shut_down`
`units_out_of_service_transition` = `unit_state_transition`
`units_out_of_service_contiguous` = `min_up_time`

New constraint:

min_scheduled_outage_duration:
sum(t, units_out_of_service(u,y)) >= scheduled_outage_duration(u) * number_of_units(u)

In a second piece, we can introduce a piecewise linear penalty function into the objective function to maximise the capacity margin (minimise LOLE) over the optimisation window

**Comment by manuelma** [comment]
Just to check if I'm following, this `sum(t, units_out_of_service(u,t)) >= scheduled_outage_duration(u) * number_of_units(u)` doesn't "ensure that the outage is taken as a continuous block", does it?

**Comment by DillonJ** [comment]
No - that constraint just ensures that the required amount of outage time is taken - but not that it's contiguous. The constraint `units_out_of_service_contiguous` does this, which is analagous to the `min_up_time` constraint
