### ISSUE TITLE
Epic: Multi-year investment feature

### ISSUE THREAD

**Issue by datejada** [spine-tools/SpineOpt.jl#908]
**Description**
The multi-year investments in SpineOpt are based on the proposal in discussion #476

**Steps**
Please create an independent issue for each step (and even consider splitting this one if needed). The goal is that each issue can be merged with passing the existing and new tests to continue to the next one. Create a new branch from the master for each step to merge individually.

- [x] #909
- [x] #910
- [x] #1041
- [x] Test vintage investment through input data (see last Maren's comment in Discussion #476)
- [x] #1050
- [x] #1051
- [x] #1057
- [x] ~#911~
- [x] ~#976~
- [x] ~#977~
- [x] ~#912~
- [x] #689 
- [x] #913
- [x] #914
- [x] #1070

**Additional context**
Related PR ##448, and Discussion #476

**Comment by manuelma** [comment]
Here it would be nice to have the story behind the change - the full design. What's the current situation, what is missing and what we want to include/change then. This would help us understand the changes in the code much better.

Maybe https://github.com/spine-tools/SpineOpt.jl/pull/448 and https://github.com/spine-tools/SpineOpt.jl/discussions/476 have the information but it would be nice to have a summary directly here, or at least a link to a single post or document containing the design.
