### ISSUE TITLE
Update the documentation (e.g., formulation and features)

### ISSUE THREAD

**Issue by datejada** [spine-tools/SpineOpt.jl#913]
For multi-year investment

**Comment by datejada** [comment]
@gnawin This is the last issue in the Epic. Please double-check if we still need it (meaning, there are still things to update in the documentation) or if we can close it, considering the latest updates you have made in other issues in the Epic.

Thanks!

**Comment by gnawin** [comment]
@datejada thanks for the heads-up. Yes, we still need it because this is to include some information on the formulation in the concepts parts (in addition to the tutorials). Basically to give links for the documents we have. I'll do this sometime this week.
