### ISSUE TITLE
User from Node constraint

### ISSUE THREAD

**Issue by shuo1990** [spine-tools/SpineOpt.jl#955]
Hi,

I place my V2H charger in the User, and EV SOC in the Node. I have set the minimum SOC 10%. How can I set an additional constraint of <30% disallow the EV to discharge?

Kind regards
Shuo

**Comment by shuo1990** [comment]
Thank you Antti.

Hopefully, my issue will be answered as soon as possible.

Kind regards,

Shuo



________________________________

**Comment by DillonJ** [comment]
Duplicate of https://github.com/spine-tools/SpineOpt.jl/issues/954
