### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by fbozzolo** [spine-tools/SpineOpt.jl#958]
I was reading the documentation of Spine Opt and found a mistake in one constraint inequation. 
In "Mathematical Formulation > Constraints > Cyclic condition on node state variable" the inequation should be "smaller than" and not "bigger than" according to the order that is depicted.

**Comment by tarskul** [comment]
Ok,thanks for spotting this.

I've made the change in the code so it should update the next time the documentation is built.
