### ISSUE TITLE
new parameter for connection__node__node relationship class

### ISSUE THREAD

**Issue by Alireza64z** [spine-tools/SpineOpt.jl#978]
I'm looking to introduce a parameter, such as "fix_ratio_out_out_unit_flow," for the "connection__node__node" relationship class. The objective is to ensure that the flow of connections to two different nodes remains identical. For instance, in computing the System Non-Synchronous Penetration (SNSP) limit, it's essential to have the import or export power value from one node to match that of another node. To enforce this constraint, another node should be designated to maintain an identical connection flow outgoing to the main node.

Presently, we have the "fix_ratio_out_in_connection_flow" parameter available for the "connection__node__node" relationship. However, it would be beneficial to incorporate two additional parameters: "fix_ratio_out_out_connection_flow" and "fix_ratio_in_in_connection_flow" to cater to this specific requirement.

Alternatively, if there are alternative approaches to model this problem effectively, I would greatly appreciate your guidance.

**Comment by tarskul** [comment]
I'm having troubles understanding what you are trying to do. But SpineOpt should be quite flexible in its definitions of the relations, as you can see in the documentation of [how to define an efficiency](https://spine-tools.github.io/SpineOpt.jl/latest/how_to/define_an_efficiency/). That should also work for a fixed flow of a connection.

So, for me the question is whether you can make the first system below or do you need to make the second system?
![alireza64zbis](https://github.com/spine-tools/SpineOpt.jl/assets/120471470/33a08d56-522c-4f3a-bc2b-0706b31f31a4)

![alireza64z](https://github.com/spine-tools/SpineOpt.jl/assets/120471470/f462b0f3-7d89-458b-95bf-0698abcd0c76)

**Comment by Alireza64z** [comment]
Hello, and thank you for your guide. To better illustrate my issue, please refer to the attached figure.

I have a connection, or interconnector line (IE-GB), between two nodes: ELEC_IE and ELEC_GB. This connection allows for power exchange between the two nodes, enabling import or export modes.

My goal is to establish the same power flow for import and export modes between the node ELEC_IE and a new node named SNSP. In other words, I want the power flow value for import/export from/to the ELEC_IE node to be consistent with the power flow from/to the SNSP node (Like setting a `fix_ratio_out_out_connection_flow` parameter in the `connection(IE-GB)_node(ELEC_IE)_node(SNSP)` relation to 1).
<img width="417" alt="connection-node-node" src="https://github.com/spine-tools/SpineOpt.jl/assets/141316670/428cbdaa-0d15-47b0-87ad-21e01c141be6">


The SNSP node is intended to model a constraint that limits flows from certain connections and units. I am looking for the appropriate relationship parameter from the Connection_node_node relation that will ensure that the outflow from the IE-GB connection to the ELEC_IE node matches the outflow from the IE-GB connection to the SNSP node.

Can you please advise on which parameter would best achieve this consistency?

**Comment by tarskul** [comment]
As I was trying to implement your example, I realised that I falsely assumed that connection had these relations similar to units. Connections and units are very much related but they are not completely the same. I know it may feel weird, but could you replace the connection by a unit and see whether you can obtain the desired results? (you can also try a user constraint but that is more difficult)

In the meanwhile I'll discuss the extension of the connection flow input/output relations in an upcoming developer meeting.

**Comment by clizbe** [comment]
@Alireza64z Did this solution work for you?

**Comment by Alireza64z** [comment]
Yes, by focusing on the unit rather than the connection, I temporarily resolved the issue. Additionally, I utilized user constraints to address my challenges further. 
Thank you.
